// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.SQLException;
// imports+ 

// imports- 



/**
 * Listener that is notified of city table changes.
 */
public interface CityListener
// extends+ 

// extends- 

{
    /**
     * Invoked just before inserting a CityBean record into the database.
     *
     * @param pObject the CityBean that is about to be inserted
     */
    public void beforeInsert(CityBean pObject) throws SQLException;


    /**
     * Invoked just after a CityBean record is inserted in the database.
     *
     * @param pObject the CityBean that was just inserted
     */
    public void afterInsert(CityBean pObject) throws SQLException;


    /**
     * Invoked just before updating a CityBean record in the database.
     *
     * @param pObject the CityBean that is about to be updated
     */
    public void beforeUpdate(CityBean pObject) throws SQLException;


    /**
     * Invoked just after updating a CityBean record in the database.
     *
     * @param pObject the CityBean that was just updated
     */
    public void afterUpdate(CityBean pObject) throws SQLException;


// class+ 

// class- 

}
