// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

// imports+ 

// imports- 


public class ProductBean
// extends+ 

// extends- 

{
    private Integer productid;
    private boolean productid_is_modified = false;
    private boolean productid_is_initialized = false;
    
    private String name;
    private boolean name_is_modified = false;
    private boolean name_is_initialized = false;
    
    private String description;
    private boolean description_is_modified = false;
    private boolean description_is_initialized = false;
    
    private Integer producttypeid;
    private boolean producttypeid_is_modified = false;
    private boolean producttypeid_is_initialized = false;
    
    private Integer unitsid;
    private boolean unitsid_is_modified = false;
    private boolean unitsid_is_initialized = false;
    
    private boolean _isNew = true;
    
    /**
     * Do not use this constructor directly, please use the factory method
     * available in the associated manager.
     */
    ProductBean()
    {
    }
    
    /**
     * Getter method for productid.
     * <br>
     * PRIMARY KEY.<br>
     * Meta Data Information (in progress):
     * <ul>
     * <li>full name: product.productid
     * <li>column size: 4
     * <li>jdbc type returned by the driver: Types.INTEGER
     * </ul>
     *
     * @return the value of productid
     */
    public Integer getProductid()
    {
        return productid; 
    }

    /**
     * Setter method for productid.
     * <br>
     * The new value is set only if compareTo() says it is different,
     * or if one of either the new value or the current value is null.
     * In case the new value is different, it is set and the field is marked as 'modified'.
     *
     * @param newVal the new value to be assigned to productid
     */
    public void setProductid(Integer newVal) {
        if ((newVal != null && this.productid != null && (newVal.compareTo(this.productid) == 0)) || 
            (newVal == null && this.productid == null && productid_is_initialized)) {
            return; 
        } 
        this.productid = newVal; 
        productid_is_modified = true; 
        productid_is_initialized = true; 
    }

    /**
     * Setter method for productid.
     * <br>
     * Convenient for those who do not want to deal with Objects for primary types.
     *
     * @param newVal the new value to be assigned to productid
     */
    public void setProductid(int newVal) {
        setProductid(new Integer(newVal));
    }

    /**
     * Determines if the productid has been modified.
     *
     * @return true if the field has been modified, false if the field has not been modified
     */
    public boolean isProductidModified() {
        return productid_is_modified; 
    }

    /**
     * Determines if the productid has been initialized.
     * <br>
     * It is useful to determine if a field is null on purpose or just because it has not been initialized.
     *
     * @return true if the field has been initialized, false otherwise
     */
    public boolean isProductidInitialized() {
        return productid_is_initialized; 
    }

    /**
     * Getter method for name.
     * <br>
     * Meta Data Information (in progress):
     * <ul>
     * <li>full name: product.name
     * <li>column size: -1
     * <li>jdbc type returned by the driver: Types.VARCHAR
     * </ul>
     *
     * @return the value of name
     */
    public String getName()
    {
        return name; 
    }

    /**
     * Setter method for name.
     * <br>
     * The new value is set only if compareTo() says it is different,
     * or if one of either the new value or the current value is null.
     * In case the new value is different, it is set and the field is marked as 'modified'.
     *
     * @param newVal the new value to be assigned to name
     */
    public void setName(String newVal) {
        if ((newVal != null && this.name != null && (newVal.compareTo(this.name) == 0)) || 
            (newVal == null && this.name == null && name_is_initialized)) {
            return; 
        } 
        this.name = newVal; 
        name_is_modified = true; 
        name_is_initialized = true; 
    }

    /**
     * Determines if the name has been modified.
     *
     * @return true if the field has been modified, false if the field has not been modified
     */
    public boolean isNameModified() {
        return name_is_modified; 
    }

    /**
     * Determines if the name has been initialized.
     * <br>
     * It is useful to determine if a field is null on purpose or just because it has not been initialized.
     *
     * @return true if the field has been initialized, false otherwise
     */
    public boolean isNameInitialized() {
        return name_is_initialized; 
    }

    /**
     * Getter method for description.
     * <br>
     * Meta Data Information (in progress):
     * <ul>
     * <li>full name: product.description
     * <li>column size: -1
     * <li>jdbc type returned by the driver: Types.VARCHAR
     * </ul>
     *
     * @return the value of description
     */
    public String getDescription()
    {
        return description; 
    }

    /**
     * Setter method for description.
     * <br>
     * The new value is set only if compareTo() says it is different,
     * or if one of either the new value or the current value is null.
     * In case the new value is different, it is set and the field is marked as 'modified'.
     *
     * @param newVal the new value to be assigned to description
     */
    public void setDescription(String newVal) {
        if ((newVal != null && this.description != null && (newVal.compareTo(this.description) == 0)) || 
            (newVal == null && this.description == null && description_is_initialized)) {
            return; 
        } 
        this.description = newVal; 
        description_is_modified = true; 
        description_is_initialized = true; 
    }

    /**
     * Determines if the description has been modified.
     *
     * @return true if the field has been modified, false if the field has not been modified
     */
    public boolean isDescriptionModified() {
        return description_is_modified; 
    }

    /**
     * Determines if the description has been initialized.
     * <br>
     * It is useful to determine if a field is null on purpose or just because it has not been initialized.
     *
     * @return true if the field has been initialized, false otherwise
     */
    public boolean isDescriptionInitialized() {
        return description_is_initialized; 
    }

    /**
     * Getter method for producttypeid.
     * <br>
     * Meta Data Information (in progress):
     * <ul>
     * <li>full name: product.producttypeid
     * <li> foreign key: producttype.producttypeid
     * <li>column size: 4
     * <li>jdbc type returned by the driver: Types.INTEGER
     * </ul>
     *
     * @return the value of producttypeid
     */
    public Integer getProducttypeid()
    {
        return producttypeid; 
    }

    /**
     * Setter method for producttypeid.
     * <br>
     * The new value is set only if compareTo() says it is different,
     * or if one of either the new value or the current value is null.
     * In case the new value is different, it is set and the field is marked as 'modified'.
     *
     * @param newVal the new value to be assigned to producttypeid
     */
    public void setProducttypeid(Integer newVal) {
        if ((newVal != null && this.producttypeid != null && (newVal.compareTo(this.producttypeid) == 0)) || 
            (newVal == null && this.producttypeid == null && producttypeid_is_initialized)) {
            return; 
        } 
        this.producttypeid = newVal; 
        producttypeid_is_modified = true; 
        producttypeid_is_initialized = true; 
    }

    /**
     * Setter method for producttypeid.
     * <br>
     * Convenient for those who do not want to deal with Objects for primary types.
     *
     * @param newVal the new value to be assigned to producttypeid
     */
    public void setProducttypeid(int newVal) {
        setProducttypeid(new Integer(newVal));
    }

    /**
     * Determines if the producttypeid has been modified.
     *
     * @return true if the field has been modified, false if the field has not been modified
     */
    public boolean isProducttypeidModified() {
        return producttypeid_is_modified; 
    }

    /**
     * Determines if the producttypeid has been initialized.
     * <br>
     * It is useful to determine if a field is null on purpose or just because it has not been initialized.
     *
     * @return true if the field has been initialized, false otherwise
     */
    public boolean isProducttypeidInitialized() {
        return producttypeid_is_initialized; 
    }

    /**
     * Getter method for unitsid.
     * <br>
     * Meta Data Information (in progress):
     * <ul>
     * <li>full name: product.unitsid
     * <li> foreign key: units.unitsid
     * <li>column size: 4
     * <li>jdbc type returned by the driver: Types.INTEGER
     * </ul>
     *
     * @return the value of unitsid
     */
    public Integer getUnitsid()
    {
        return unitsid; 
    }

    /**
     * Setter method for unitsid.
     * <br>
     * The new value is set only if compareTo() says it is different,
     * or if one of either the new value or the current value is null.
     * In case the new value is different, it is set and the field is marked as 'modified'.
     *
     * @param newVal the new value to be assigned to unitsid
     */
    public void setUnitsid(Integer newVal) {
        if ((newVal != null && this.unitsid != null && (newVal.compareTo(this.unitsid) == 0)) || 
            (newVal == null && this.unitsid == null && unitsid_is_initialized)) {
            return; 
        } 
        this.unitsid = newVal; 
        unitsid_is_modified = true; 
        unitsid_is_initialized = true; 
    }

    /**
     * Setter method for unitsid.
     * <br>
     * Convenient for those who do not want to deal with Objects for primary types.
     *
     * @param newVal the new value to be assigned to unitsid
     */
    public void setUnitsid(int newVal) {
        setUnitsid(new Integer(newVal));
    }

    /**
     * Determines if the unitsid has been modified.
     *
     * @return true if the field has been modified, false if the field has not been modified
     */
    public boolean isUnitsidModified() {
        return unitsid_is_modified; 
    }

    /**
     * Determines if the unitsid has been initialized.
     * <br>
     * It is useful to determine if a field is null on purpose or just because it has not been initialized.
     *
     * @return true if the field has been initialized, false otherwise
     */
    public boolean isUnitsidInitialized() {
        return unitsid_is_initialized; 
    }

    /**
     * Determines if the current object is new.
     *
     * @return true if the current object is new, false if the object is not new
     */
    public boolean isNew() {
        return _isNew;
    }

    /**
     * Specifies to the object if it has been set as new.
     *
     * @param isNew the boolean value to be assigned to the isNew field
     */
    public void isNew(boolean isNew) {
        this._isNew = isNew;
    }

    /**
     * Determines if the object has been modified since the last time this method was called.
     * <br>
     * We can also determine if this object has ever been modified since its creation.
     *
     * @return true if the object has been modified, false if the object has not been modified
     */
    public boolean isModified() {
        return productid_is_modified || 
		name_is_modified || 
		description_is_modified || 
		producttypeid_is_modified || 
		unitsid_is_modified;
    }

    /**
     * Resets the object modification status to 'not modified'.
     */
    public void resetIsModified() {
        productid_is_modified = false;
        name_is_modified = false;
        description_is_modified = false;
        producttypeid_is_modified = false;
        unitsid_is_modified = false;
    }

    /**
     * Copies the passed bean into the current bean.
     *
     * @param bean the bean to copy into the current bean
     */
    public void copy(ProductBean bean) {
        setProductid(bean.getProductid());
        setName(bean.getName());
        setDescription(bean.getDescription());
        setProducttypeid(bean.getProducttypeid());
        setUnitsid(bean.getUnitsid());
    }

    /**
     * Returns the object string representation.
     *
     * @return the object as a string
     */
    public String toString() {
        return   "\n[product] "
                 + "\n - product.productid = " + (productid_is_initialized ? ("[" + (productid == null ? null : productid.toString()) + "]") : "not initialized") + ""
                 + "\n - product.name = " + (name_is_initialized ? ("[" + (name == null ? null : name.toString()) + "]") : "not initialized") + ""
                 + "\n - product.description = " + (description_is_initialized ? ("[" + (description == null ? null : description.toString()) + "]") : "not initialized") + ""
                 + "\n - product.producttypeid = " + (producttypeid_is_initialized ? ("[" + (producttypeid == null ? null : producttypeid.toString()) + "]") : "not initialized") + ""
                 + "\n - product.unitsid = " + (unitsid_is_initialized ? ("[" + (unitsid == null ? null : unitsid.toString()) + "]") : "not initialized") + ""
            ;
    }

// class+ 

// class- 

}
