// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of closedate table changes.
 */
public interface ClosedateListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a ClosedateBean record into the database.
     *
     * @param pObject the ClosedateBean that is about to be inserted
     */
    public void beforeInsert(ClosedateBean pObject) throws SQLException;


    /**
     * Invoked just after a ClosedateBean record is inserted in the database.
     *
     * @param pObject the ClosedateBean that was just inserted
     */
    public void afterInsert(ClosedateBean pObject) throws SQLException;


    /**
     * Invoked just before updating a ClosedateBean record in the database.
     *
     * @param pObject the ClosedateBean that is about to be updated
     */
    public void beforeUpdate(ClosedateBean pObject) throws SQLException;


    /**
     * Invoked just after updating a ClosedateBean record in the database.
     *
     * @param pObject the ClosedateBean that was just updated
     */
    public void afterUpdate(ClosedateBean pObject) throws SQLException;


// class+ 

// class- 
}
