// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.SQLException;
// imports+ 

// imports- 



/**
 * Listener that is notified of customer table changes.
 */
public interface CustomerListener
// extends+ 

// extends- 

{
    /**
     * Invoked just before inserting a CustomerBean record into the database.
     *
     * @param pObject the CustomerBean that is about to be inserted
     */
    public void beforeInsert(CustomerBean pObject) throws SQLException;


    /**
     * Invoked just after a CustomerBean record is inserted in the database.
     *
     * @param pObject the CustomerBean that was just inserted
     */
    public void afterInsert(CustomerBean pObject) throws SQLException;


    /**
     * Invoked just before updating a CustomerBean record in the database.
     *
     * @param pObject the CustomerBean that is about to be updated
     */
    public void beforeUpdate(CustomerBean pObject) throws SQLException;


    /**
     * Invoked just after updating a CustomerBean record in the database.
     *
     * @param pObject the CustomerBean that was just updated
     */
    public void afterUpdate(CustomerBean pObject) throws SQLException;


// class+ 

// class- 

}
