// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.SQLException;
// imports+ 

// imports- 



/**
 * Listener that is notified of repcat table changes.
 */
public interface RepcatListener
// extends+ 

// extends- 

{
    /**
     * Invoked just before inserting a RepcatBean record into the database.
     *
     * @param pObject the RepcatBean that is about to be inserted
     */
    public void beforeInsert(RepcatBean pObject) throws SQLException;


    /**
     * Invoked just after a RepcatBean record is inserted in the database.
     *
     * @param pObject the RepcatBean that was just inserted
     */
    public void afterInsert(RepcatBean pObject) throws SQLException;


    /**
     * Invoked just before updating a RepcatBean record in the database.
     *
     * @param pObject the RepcatBean that is about to be updated
     */
    public void beforeUpdate(RepcatBean pObject) throws SQLException;


    /**
     * Invoked just after updating a RepcatBean record in the database.
     *
     * @param pObject the RepcatBean that was just updated
     */
    public void afterUpdate(RepcatBean pObject) throws SQLException;


// class+ 

// class- 

}
