// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.SQLException;
// imports+ 

// imports- 



/**
 * Listener that is notified of roomstatuscolor table changes.
 */
public interface RoomstatuscolorListener
// extends+ 

// extends- 

{
    /**
     * Invoked just before inserting a RoomstatuscolorBean record into the database.
     *
     * @param pObject the RoomstatuscolorBean that is about to be inserted
     */
    public void beforeInsert(RoomstatuscolorBean pObject) throws SQLException;


    /**
     * Invoked just after a RoomstatuscolorBean record is inserted in the database.
     *
     * @param pObject the RoomstatuscolorBean that was just inserted
     */
    public void afterInsert(RoomstatuscolorBean pObject) throws SQLException;


    /**
     * Invoked just before updating a RoomstatuscolorBean record in the database.
     *
     * @param pObject the RoomstatuscolorBean that is about to be updated
     */
    public void beforeUpdate(RoomstatuscolorBean pObject) throws SQLException;


    /**
     * Invoked just after updating a RoomstatuscolorBean record in the database.
     *
     * @param pObject the RoomstatuscolorBean that was just updated
     */
    public void afterUpdate(RoomstatuscolorBean pObject) throws SQLException;


// class+ 

// class- 

}
