// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.SQLException;
// imports+ 

// imports- 



/**
 * Listener that is notified of transportationmode table changes.
 */
public interface TransportationmodeListener
// extends+ 

// extends- 

{
    /**
     * Invoked just before inserting a TransportationmodeBean record into the database.
     *
     * @param pObject the TransportationmodeBean that is about to be inserted
     */
    public void beforeInsert(TransportationmodeBean pObject) throws SQLException;


    /**
     * Invoked just after a TransportationmodeBean record is inserted in the database.
     *
     * @param pObject the TransportationmodeBean that was just inserted
     */
    public void afterInsert(TransportationmodeBean pObject) throws SQLException;


    /**
     * Invoked just before updating a TransportationmodeBean record in the database.
     *
     * @param pObject the TransportationmodeBean that is about to be updated
     */
    public void beforeUpdate(TransportationmodeBean pObject) throws SQLException;


    /**
     * Invoked just after updating a TransportationmodeBean record in the database.
     *
     * @param pObject the TransportationmodeBean that was just updated
     */
    public void afterUpdate(TransportationmodeBean pObject) throws SQLException;


// class+ 

// class- 

}
