// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.SQLException;
// imports+ 

// imports- 



/**
 * Listener that is notified of v_blockroom table changes.
 */
public interface VBlockroomListener
// extends+ 

// extends- 

{
    /**
     * Invoked just before inserting a VBlockroomBean record into the database.
     *
     * @param pObject the VBlockroomBean that is about to be inserted
     */
    public void beforeInsert(VBlockroomBean pObject) throws SQLException;


    /**
     * Invoked just after a VBlockroomBean record is inserted in the database.
     *
     * @param pObject the VBlockroomBean that was just inserted
     */
    public void afterInsert(VBlockroomBean pObject) throws SQLException;


    /**
     * Invoked just before updating a VBlockroomBean record in the database.
     *
     * @param pObject the VBlockroomBean that is about to be updated
     */
    public void beforeUpdate(VBlockroomBean pObject) throws SQLException;


    /**
     * Invoked just after updating a VBlockroomBean record in the database.
     *
     * @param pObject the VBlockroomBean that was just updated
     */
    public void afterUpdate(VBlockroomBean pObject) throws SQLException;


// class+ 

// class- 

}
