// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.SQLException;
// imports+ 

// imports- 



/**
 * Listener that is notified of vs_bsource table changes.
 */
public interface VsBsourceListener
// extends+ 

// extends- 

{
    /**
     * Invoked just before inserting a VsBsourceBean record into the database.
     *
     * @param pObject the VsBsourceBean that is about to be inserted
     */
    public void beforeInsert(VsBsourceBean pObject) throws SQLException;


    /**
     * Invoked just after a VsBsourceBean record is inserted in the database.
     *
     * @param pObject the VsBsourceBean that was just inserted
     */
    public void afterInsert(VsBsourceBean pObject) throws SQLException;


    /**
     * Invoked just before updating a VsBsourceBean record in the database.
     *
     * @param pObject the VsBsourceBean that is about to be updated
     */
    public void beforeUpdate(VsBsourceBean pObject) throws SQLException;


    /**
     * Invoked just after updating a VsBsourceBean record in the database.
     *
     * @param pObject the VsBsourceBean that was just updated
     */
    public void afterUpdate(VsBsourceBean pObject) throws SQLException;


// class+ 

// class- 

}
