// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.util.Comparator;
// imports+ 

// imports- 


/**
 * Comparator class is used to sort the VsCityledgerBean objects.
 */
public class VsCityledgerComparator implements Comparator
// extends+ 

// extends- 

{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for VsCityledgerComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new VsCityledgerComparator(VsCityledgerManager.REGDATE, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>VsCityledgerManager.ID_REGDATE
     *   <li>VsCityledgerManager.ID_GUEST
     *   <li>VsCityledgerManager.ID_ARRAIVALDATE
     *   <li>VsCityledgerManager.ID_DEPARTUREDATE
     *   <li>VsCityledgerManager.ID_REFERENCE
     * </ul>
     */
    public VsCityledgerComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for VsCityledgerComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new VsCityledgerComparator(VsCityledgerManager.REGDATE, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>VsCityledgerManager.ID_REGDATE
     *   <li>VsCityledgerManager.ID_GUEST
     *   <li>VsCityledgerManager.ID_ARRAIVALDATE
     *   <li>VsCityledgerManager.ID_DEPARTUREDATE
     *   <li>VsCityledgerManager.ID_REFERENCE
     *   <li>VsCityledgerManager.ID_CREDITS
     *   <li>VsCityledgerManager.ID_DEBITS
     *   <li>VsCityledgerManager.ID_BALANCE
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public VsCityledgerComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        VsCityledgerBean b1 = (VsCityledgerBean)pObj1;
        VsCityledgerBean b2 = (VsCityledgerBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case VsCityledgerManager.ID_REGDATE:
                if (b1.getRegdate() == null && b2.getRegdate() != null) {
                    iReturn = -1;
                } else if (b1.getRegdate() == null && b2.getRegdate() == null) {
                    iReturn = 0;
                } else if (b1.getRegdate() != null && b2.getRegdate() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRegdate().compareTo(b2.getRegdate());
                }
                break;
            case VsCityledgerManager.ID_GUEST:
                if (b1.getGuest() == null && b2.getGuest() != null) {
                    iReturn = -1;
                } else if (b1.getGuest() == null && b2.getGuest() == null) {
                    iReturn = 0;
                } else if (b1.getGuest() != null && b2.getGuest() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getGuest().compareTo(b2.getGuest());
                }
                break;
            case VsCityledgerManager.ID_ARRAIVALDATE:
                if (b1.getArraivaldate() == null && b2.getArraivaldate() != null) {
                    iReturn = -1;
                } else if (b1.getArraivaldate() == null && b2.getArraivaldate() == null) {
                    iReturn = 0;
                } else if (b1.getArraivaldate() != null && b2.getArraivaldate() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getArraivaldate().compareTo(b2.getArraivaldate());
                }
                break;
            case VsCityledgerManager.ID_DEPARTUREDATE:
                if (b1.getDeparturedate() == null && b2.getDeparturedate() != null) {
                    iReturn = -1;
                } else if (b1.getDeparturedate() == null && b2.getDeparturedate() == null) {
                    iReturn = 0;
                } else if (b1.getDeparturedate() != null && b2.getDeparturedate() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getDeparturedate().compareTo(b2.getDeparturedate());
                }
                break;
            case VsCityledgerManager.ID_REFERENCE:
                if (b1.getReference() == null && b2.getReference() != null) {
                    iReturn = -1;
                } else if (b1.getReference() == null && b2.getReference() == null) {
                    iReturn = 0;
                } else if (b1.getReference() != null && b2.getReference() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getReference().compareTo(b2.getReference());
                }
                break;
            default: 
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 

}
