// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.util.Comparator;
// imports+ 

// imports- 


/**
 * Comparator class is used to sort the VsNoshowBean objects.
 */
public class VsNoshowComparator implements Comparator
// extends+ 

// extends- 

{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for VsNoshowComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new VsNoshowComparator(VsNoshowManager.RESERVATIONID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>VsNoshowManager.ID_RESERVATIONID
     *   <li>VsNoshowManager.ID_GUEST
     *   <li>VsNoshowManager.ID_ARRAIVALDATE
     *   <li>VsNoshowManager.ID_DEPARTUREDATE
     *   <li>VsNoshowManager.ID_NUM
     *   <li>VsNoshowManager.ID_CHARGES
     *   <li>VsNoshowManager.ID_PAID
     *   <li>VsNoshowManager.ID_BALANCE
     *   <li>VsNoshowManager.ID_SOURCE
     *   <li>VsNoshowManager.ID_NOSHOWBY
     *   <li>VsNoshowManager.ID_REGDATE
     *   <li>VsNoshowManager.ID_REMARK
     *   <li>VsNoshowManager.ID_REGBYID
     *   <li>VsNoshowManager.ID_BSOURCEID
     *   <li>VsNoshowManager.ID_ROOMTYPEID
     *   <li>VsNoshowManager.ID_RATETYPEID
     * </ul>
     */
    public VsNoshowComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for VsNoshowComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new VsNoshowComparator(VsNoshowManager.RESERVATIONID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>VsNoshowManager.ID_RESERVATIONID
     *   <li>VsNoshowManager.ID_GUEST
     *   <li>VsNoshowManager.ID_ARRAIVALDATE
     *   <li>VsNoshowManager.ID_DEPARTUREDATE
     *   <li>VsNoshowManager.ID_NUM
     *   <li>VsNoshowManager.ID_CHARGES
     *   <li>VsNoshowManager.ID_PAID
     *   <li>VsNoshowManager.ID_BALANCE
     *   <li>VsNoshowManager.ID_SOURCE
     *   <li>VsNoshowManager.ID_NOSHOWBY
     *   <li>VsNoshowManager.ID_REGDATE
     *   <li>VsNoshowManager.ID_REMARK
     *   <li>VsNoshowManager.ID_REGBYID
     *   <li>VsNoshowManager.ID_BSOURCEID
     *   <li>VsNoshowManager.ID_ROOMTYPEID
     *   <li>VsNoshowManager.ID_RATETYPEID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public VsNoshowComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        VsNoshowBean b1 = (VsNoshowBean)pObj1;
        VsNoshowBean b2 = (VsNoshowBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case VsNoshowManager.ID_RESERVATIONID:
                if (b1.getReservationid() == null && b2.getReservationid() != null) {
                    iReturn = -1;
                } else if (b1.getReservationid() == null && b2.getReservationid() == null) {
                    iReturn = 0;
                } else if (b1.getReservationid() != null && b2.getReservationid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getReservationid().compareTo(b2.getReservationid());
                }
                break;
            case VsNoshowManager.ID_GUEST:
                if (b1.getGuest() == null && b2.getGuest() != null) {
                    iReturn = -1;
                } else if (b1.getGuest() == null && b2.getGuest() == null) {
                    iReturn = 0;
                } else if (b1.getGuest() != null && b2.getGuest() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getGuest().compareTo(b2.getGuest());
                }
                break;
            case VsNoshowManager.ID_ARRAIVALDATE:
                if (b1.getArraivaldate() == null && b2.getArraivaldate() != null) {
                    iReturn = -1;
                } else if (b1.getArraivaldate() == null && b2.getArraivaldate() == null) {
                    iReturn = 0;
                } else if (b1.getArraivaldate() != null && b2.getArraivaldate() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getArraivaldate().compareTo(b2.getArraivaldate());
                }
                break;
            case VsNoshowManager.ID_DEPARTUREDATE:
                if (b1.getDeparturedate() == null && b2.getDeparturedate() != null) {
                    iReturn = -1;
                } else if (b1.getDeparturedate() == null && b2.getDeparturedate() == null) {
                    iReturn = 0;
                } else if (b1.getDeparturedate() != null && b2.getDeparturedate() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getDeparturedate().compareTo(b2.getDeparturedate());
                }
                break;
            case VsNoshowManager.ID_NUM:
                if (b1.getNum() == null && b2.getNum() != null) {
                    iReturn = -1;
                } else if (b1.getNum() == null && b2.getNum() == null) {
                    iReturn = 0;
                } else if (b1.getNum() != null && b2.getNum() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getNum().compareTo(b2.getNum());
                }
                break;
            case VsNoshowManager.ID_CHARGES:
                if (b1.getCharges() == null && b2.getCharges() != null) {
                    iReturn = -1;
                } else if (b1.getCharges() == null && b2.getCharges() == null) {
                    iReturn = 0;
                } else if (b1.getCharges() != null && b2.getCharges() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getCharges().compareTo(b2.getCharges());
                }
                break;
            case VsNoshowManager.ID_PAID:
                if (b1.getPaid() == null && b2.getPaid() != null) {
                    iReturn = -1;
                } else if (b1.getPaid() == null && b2.getPaid() == null) {
                    iReturn = 0;
                } else if (b1.getPaid() != null && b2.getPaid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getPaid().compareTo(b2.getPaid());
                }
                break;
            case VsNoshowManager.ID_BALANCE:
                if (b1.getBalance() == null && b2.getBalance() != null) {
                    iReturn = -1;
                } else if (b1.getBalance() == null && b2.getBalance() == null) {
                    iReturn = 0;
                } else if (b1.getBalance() != null && b2.getBalance() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getBalance().compareTo(b2.getBalance());
                }
                break;
            case VsNoshowManager.ID_SOURCE:
                if (b1.getSource() == null && b2.getSource() != null) {
                    iReturn = -1;
                } else if (b1.getSource() == null && b2.getSource() == null) {
                    iReturn = 0;
                } else if (b1.getSource() != null && b2.getSource() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getSource().compareTo(b2.getSource());
                }
                break;
            case VsNoshowManager.ID_NOSHOWBY:
                if (b1.getNoshowby() == null && b2.getNoshowby() != null) {
                    iReturn = -1;
                } else if (b1.getNoshowby() == null && b2.getNoshowby() == null) {
                    iReturn = 0;
                } else if (b1.getNoshowby() != null && b2.getNoshowby() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getNoshowby().compareTo(b2.getNoshowby());
                }
                break;
            case VsNoshowManager.ID_REGDATE:
                if (b1.getRegdate() == null && b2.getRegdate() != null) {
                    iReturn = -1;
                } else if (b1.getRegdate() == null && b2.getRegdate() == null) {
                    iReturn = 0;
                } else if (b1.getRegdate() != null && b2.getRegdate() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRegdate().compareTo(b2.getRegdate());
                }
                break;
            case VsNoshowManager.ID_REMARK:
                if (b1.getRemark() == null && b2.getRemark() != null) {
                    iReturn = -1;
                } else if (b1.getRemark() == null && b2.getRemark() == null) {
                    iReturn = 0;
                } else if (b1.getRemark() != null && b2.getRemark() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRemark().compareTo(b2.getRemark());
                }
                break;
            case VsNoshowManager.ID_REGBYID:
                if (b1.getRegbyid() == null && b2.getRegbyid() != null) {
                    iReturn = -1;
                } else if (b1.getRegbyid() == null && b2.getRegbyid() == null) {
                    iReturn = 0;
                } else if (b1.getRegbyid() != null && b2.getRegbyid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRegbyid().compareTo(b2.getRegbyid());
                }
                break;
            case VsNoshowManager.ID_BSOURCEID:
                if (b1.getBsourceid() == null && b2.getBsourceid() != null) {
                    iReturn = -1;
                } else if (b1.getBsourceid() == null && b2.getBsourceid() == null) {
                    iReturn = 0;
                } else if (b1.getBsourceid() != null && b2.getBsourceid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getBsourceid().compareTo(b2.getBsourceid());
                }
                break;
            case VsNoshowManager.ID_ROOMTYPEID:
                if (b1.getRoomtypeid() == null && b2.getRoomtypeid() != null) {
                    iReturn = -1;
                } else if (b1.getRoomtypeid() == null && b2.getRoomtypeid() == null) {
                    iReturn = 0;
                } else if (b1.getRoomtypeid() != null && b2.getRoomtypeid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRoomtypeid().compareTo(b2.getRoomtypeid());
                }
                break;
            case VsNoshowManager.ID_RATETYPEID:
                if (b1.getRatetypeid() == null && b2.getRatetypeid() != null) {
                    iReturn = -1;
                } else if (b1.getRatetypeid() == null && b2.getRatetypeid() == null) {
                    iReturn = 0;
                } else if (b1.getRatetypeid() != null && b2.getRatetypeid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRatetypeid().compareTo(b2.getRatetypeid());
                }
                break;
            default: 
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 

}
