// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.util.Comparator;
// imports+ 

// imports- 

/**
 * Comparator class is used to sort the VTariffRoomtypeTarifftypeSeasonAgentBean objects.
 */
public class VTariffRoomtypeTarifftypeSeasonAgentComparator implements Comparator
// extends+ 

// extends- 
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for VTariffRoomtypeTarifftypeSeasonAgentComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new VTariffRoomtypeTarifftypeSeasonAgentComparator(VTariffRoomtypeTarifftypeSeasonAgentManager.TID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>VTariffRoomtypeTarifftypeSeasonAgentManager.ID_TID
     *   <li>VTariffRoomtypeTarifftypeSeasonAgentManager.ID_RID
     *   <li>VTariffRoomtypeTarifftypeSeasonAgentManager.ID_SID
     *   <li>VTariffRoomtypeTarifftypeSeasonAgentManager.ID_AGENTID
     * </ul>
     */
    public VTariffRoomtypeTarifftypeSeasonAgentComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for VTariffRoomtypeTarifftypeSeasonAgentComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new VTariffRoomtypeTarifftypeSeasonAgentComparator(VTariffRoomtypeTarifftypeSeasonAgentManager.TID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>VTariffRoomtypeTarifftypeSeasonAgentManager.ID_TID
     *   <li>VTariffRoomtypeTarifftypeSeasonAgentManager.ID_RID
     *   <li>VTariffRoomtypeTarifftypeSeasonAgentManager.ID_SID
     *   <li>VTariffRoomtypeTarifftypeSeasonAgentManager.ID_AGENTID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public VTariffRoomtypeTarifftypeSeasonAgentComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        VTariffRoomtypeTarifftypeSeasonAgentBean b1 = (VTariffRoomtypeTarifftypeSeasonAgentBean)pObj1;
        VTariffRoomtypeTarifftypeSeasonAgentBean b2 = (VTariffRoomtypeTarifftypeSeasonAgentBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case VTariffRoomtypeTarifftypeSeasonAgentManager.ID_TID:
                if (b1.getTid() == null && b2.getTid() != null) {
                    iReturn = -1;
                } else if (b1.getTid() == null && b2.getTid() == null) {
                    iReturn = 0;
                } else if (b1.getTid() != null && b2.getTid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getTid().compareTo(b2.getTid());
                }
                break;
            case VTariffRoomtypeTarifftypeSeasonAgentManager.ID_RID:
                if (b1.getRid() == null && b2.getRid() != null) {
                    iReturn = -1;
                } else if (b1.getRid() == null && b2.getRid() == null) {
                    iReturn = 0;
                } else if (b1.getRid() != null && b2.getRid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getRid().compareTo(b2.getRid());
                }
                break;
            case VTariffRoomtypeTarifftypeSeasonAgentManager.ID_SID:
                if (b1.getSid() == null && b2.getSid() != null) {
                    iReturn = -1;
                } else if (b1.getSid() == null && b2.getSid() == null) {
                    iReturn = 0;
                } else if (b1.getSid() != null && b2.getSid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getSid().compareTo(b2.getSid());
                }
                break;
            case VTariffRoomtypeTarifftypeSeasonAgentManager.ID_AGENTID:
                if (b1.getAgentid() == null && b2.getAgentid() != null) {
                    iReturn = -1;
                } else if (b1.getAgentid() == null && b2.getAgentid() == null) {
                    iReturn = 0;
                } else if (b1.getAgentid() != null && b2.getAgentid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getAgentid().compareTo(b2.getAgentid());
                }
                break;
            default: 
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 
}
