// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.*;
// imports+ 

// imports- 


/**
 * Handles database calls for the v_workorder table.
 */
public class VWorkorderManager
// extends+ 

// extends- 

{

    /**
     * Column workorderid of type Types.BIGINT mapped to Long.
     */
    public static final int ID_WORKORDERID = 0;
    public static final int TYPE_WORKORDERID = Types.BIGINT;
    public static final String NAME_WORKORDERID = "workorderid";

    /**
     * Column num of type Types.VARCHAR mapped to String.
     */
    public static final int ID_NUM = 1;
    public static final int TYPE_NUM = Types.VARCHAR;
    public static final String NAME_NUM = "num";

    /**
     * Column description of type Types.VARCHAR mapped to String.
     */
    public static final int ID_DESCRIPTION = 2;
    public static final int TYPE_DESCRIPTION = Types.VARCHAR;
    public static final String NAME_DESCRIPTION = "description";

    /**
     * Column category of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_CATEGORY = 3;
    public static final int TYPE_CATEGORY = Types.INTEGER;
    public static final String NAME_CATEGORY = "category";

    /**
     * Column roomid of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_ROOMID = 4;
    public static final int TYPE_ROOMID = Types.INTEGER;
    public static final String NAME_ROOMID = "roomid";

    /**
     * Column houseunitid of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_HOUSEUNITID = 5;
    public static final int TYPE_HOUSEUNITID = Types.INTEGER;
    public static final String NAME_HOUSEUNITID = "houseunitid";

    /**
     * Column blockstart of type Types.TIMESTAMP mapped to java.sql.Timestamp.
     */
    public static final int ID_BLOCKSTART = 6;
    public static final int TYPE_BLOCKSTART = Types.TIMESTAMP;
    public static final String NAME_BLOCKSTART = "blockstart";

    /**
     * Column blockend of type Types.TIMESTAMP mapped to java.sql.Timestamp.
     */
    public static final int ID_BLOCKEND = 7;
    public static final int TYPE_BLOCKEND = Types.TIMESTAMP;
    public static final String NAME_BLOCKEND = "blockend";

    /**
     * Column priority of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_PRIORITY = 8;
    public static final int TYPE_PRIORITY = Types.INTEGER;
    public static final String NAME_PRIORITY = "priority";

    /**
     * Column assignedtoid of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_ASSIGNEDTOID = 9;
    public static final int TYPE_ASSIGNEDTOID = Types.INTEGER;
    public static final String NAME_ASSIGNEDTOID = "assignedtoid";

    /**
     * Column orderstatus of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_ORDERSTATUS = 10;
    public static final int TYPE_ORDERSTATUS = Types.INTEGER;
    public static final String NAME_ORDERSTATUS = "orderstatus";

    /**
     * Column deadline of type Types.TIMESTAMP mapped to java.sql.Timestamp.
     */
    public static final int ID_DEADLINE = 11;
    public static final int TYPE_DEADLINE = Types.TIMESTAMP;
    public static final String NAME_DEADLINE = "deadline";

    /**
     * Column regdate of type Types.TIMESTAMP mapped to java.sql.Timestamp.
     */
    public static final int ID_REGDATE = 12;
    public static final int TYPE_REGDATE = Types.TIMESTAMP;
    public static final String NAME_REGDATE = "regdate";

    /**
     * Column regbyid of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_REGBYID = 13;
    public static final int TYPE_REGBYID = Types.INTEGER;
    public static final String NAME_REGBYID = "regbyid";

    /**
     * Column updatedon of type Types.TIMESTAMP mapped to java.sql.Timestamp.
     */
    public static final int ID_UPDATEDON = 14;
    public static final int TYPE_UPDATEDON = Types.TIMESTAMP;
    public static final String NAME_UPDATEDON = "updatedon";

    /**
     * Column note of type Types.VARCHAR mapped to String.
     */
    public static final int ID_NOTE = 15;
    public static final int TYPE_NOTE = Types.VARCHAR;
    public static final String NAME_NOTE = "note";

    /**
     * Column rname of type Types.VARCHAR mapped to String.
     */
    public static final int ID_RNAME = 16;
    public static final int TYPE_RNAME = Types.VARCHAR;
    public static final String NAME_RNAME = "rname";

    /**
     * Column code of type Types.VARCHAR mapped to String.
     */
    public static final int ID_CODE = 17;
    public static final int TYPE_CODE = Types.VARCHAR;
    public static final String NAME_CODE = "code";

    /**
     * Column hname of type Types.VARCHAR mapped to String.
     */
    public static final int ID_HNAME = 18;
    public static final int TYPE_HNAME = Types.VARCHAR;
    public static final String NAME_HNAME = "hname";

    /**
     * Column assignedto of type Types.VARCHAR mapped to String.
     */
    public static final int ID_ASSIGNEDTO = 19;
    public static final int TYPE_ASSIGNEDTO = Types.VARCHAR;
    public static final String NAME_ASSIGNEDTO = "assignedto";


    private static final String TABLE_NAME = "v_workorder";

    /**
     * Create an array of type string containing all the fields of the v_workorder table.
     */
    private static final String[] FIELD_NAMES = 
    {
        "v_workorder.workorderid"
        ,"v_workorder.num"
        ,"v_workorder.description"
        ,"v_workorder.category"
        ,"v_workorder.roomid"
        ,"v_workorder.houseunitid"
        ,"v_workorder.blockstart"
        ,"v_workorder.blockend"
        ,"v_workorder.priority"
        ,"v_workorder.assignedtoid"
        ,"v_workorder.orderstatus"
        ,"v_workorder.deadline"
        ,"v_workorder.regdate"
        ,"v_workorder.regbyid"
        ,"v_workorder.updatedon"
        ,"v_workorder.note"
        ,"v_workorder.rname"
        ,"v_workorder.code"
        ,"v_workorder.hname"
        ,"v_workorder.assignedto"
    };

    /**
     * Field that contains the comma separated fields of the v_workorder table.
     */
    private static final String ALL_FIELDS = "v_workorder.workorderid"
                            + ",v_workorder.num"
                            + ",v_workorder.description"
                            + ",v_workorder.category"
                            + ",v_workorder.roomid"
                            + ",v_workorder.houseunitid"
                            + ",v_workorder.blockstart"
                            + ",v_workorder.blockend"
                            + ",v_workorder.priority"
                            + ",v_workorder.assignedtoid"
                            + ",v_workorder.orderstatus"
                            + ",v_workorder.deadline"
                            + ",v_workorder.regdate"
                            + ",v_workorder.regbyid"
                            + ",v_workorder.updatedon"
                            + ",v_workorder.note"
                            + ",v_workorder.rname"
                            + ",v_workorder.code"
                            + ",v_workorder.hname"
                            + ",v_workorder.assignedto";

    private static VWorkorderManager singleton = new VWorkorderManager();

    /**
     * Get the VWorkorderManager singleton.
     *
     * @return VWorkorderManager 
     */
    synchronized public static VWorkorderManager getInstance()
    {
        return singleton;
    }

    /**
     * Sets your own VWorkorderManager instance.
     <br>
     * This is optional, by default we provide it for you.
     */
    synchronized public static void setInstance(VWorkorderManager instance)
    {
        singleton = instance;
    }


    /**
     * Creates a new VWorkorderBean instance.
     *
     * @return the new VWorkorderBean 
     */
    public VWorkorderBean createVWorkorderBean()
    {
        return new VWorkorderBean();
    }



    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from v_workorder.
     *
     * @return an array of VWorkorderManager pObject
     */
    //38
    public VWorkorderBean[] loadAll() throws SQLException 
    {
        Connection c = null;
        PreparedStatement ps = null;
        try 
        {
            c = getConnection();
            ps = c.prepareStatement("SELECT " + ALL_FIELDS + " FROM v_workorder",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            return loadByPreparedStatement(ps);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of VWorkorderBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting VWorkorderBean table 
     */
    //49
    public VWorkorderBean[] loadByWhere(String where) throws SQLException
    {
        return loadByWhere(where, null);
    }

    /**
     * Retrieves an array of VWorkorderBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param fieldList table of the field's associated constants
     * @return the resulting VWorkorderBean table 
     */
    //51
    public VWorkorderBean[] loadByWhere(String where, int[] fieldList) throws SQLException
    {
        String sql = null;
        if(fieldList == null)
            sql = "select " + ALL_FIELDS + " from v_workorder " + where;
        else
        {
            StringBuffer buff = new StringBuffer(128);
            buff.append("select ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0)
                    buff.append(",");
                buff.append(FIELD_NAMES[fieldList[i]]);
            }
            buff.append(" from v_workorder ");
            buff.append(where);
            sql = buff.toString();
            buff = null;
        }
        Connection c = null;
        Statement pStatement = null;
        ResultSet rs =  null;
        java.util.ArrayList v = null;
        try 
        {
            c = getConnection();
            pStatement = c.createStatement();
            rs =  pStatement.executeQuery(sql);
            v = new java.util.ArrayList();
            while(rs.next())
            {
                if(fieldList == null)
                    v.add(decodeRow(rs));
                else
                    v.add(decodeRow(rs, fieldList));
            }

            return (VWorkorderBean[])v.toArray(new VWorkorderBean[0]);
        }
        finally
        {
            if (v != null) { v.clear(); }
            getManager().close(pStatement, rs);
            freeConnection(c);
        }
    }


    /**
     * Deletes all rows from v_workorder table.
     * @return the number of deleted rows.
     */
    public int deleteAll() throws SQLException
    {
        return deleteByWhere("");
    }


    /**
     * Deletes rows from the v_workorder table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records. 
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     */
    public int deleteByWhere(String where) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = getConnection();
            String delByWhereSQL = "DELETE FROM v_workorder " + where;
            ps = c.prepareStatement(delByWhereSQL);
            return ps.executeUpdate();
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // SAVE 
    ///////////////////////////////////////////////////////////////////////
    /**
     * Saves the VWorkorderBean pObject into the database.
     *
     * @param pObject the VWorkorderBean pObject to be saved
     */
    //100
    public VWorkorderBean save(VWorkorderBean pObject) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer _sql = null;

        try
        {
            c = getConnection();
            if (pObject.isNew())
            { // SAVE 
                beforeInsert(pObject); // listener callback
                int _dirtyCount = 0;
                _sql = new StringBuffer("INSERT into v_workorder (");
    
                if (pObject.isWorkorderidModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("workorderid");
                    _dirtyCount++;
                }

                if (pObject.isNumModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("num");
                    _dirtyCount++;
                }

                if (pObject.isDescriptionModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("description");
                    _dirtyCount++;
                }

                if (pObject.isCategoryModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("category");
                    _dirtyCount++;
                }

                if (pObject.isRoomidModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("roomid");
                    _dirtyCount++;
                }

                if (pObject.isHouseunitidModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("houseunitid");
                    _dirtyCount++;
                }

                if (pObject.isBlockstartModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("blockstart");
                    _dirtyCount++;
                }

                if (pObject.isBlockendModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("blockend");
                    _dirtyCount++;
                }

                if (pObject.isPriorityModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("priority");
                    _dirtyCount++;
                }

                if (pObject.isAssignedtoidModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("assignedtoid");
                    _dirtyCount++;
                }

                if (pObject.isOrderstatusModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("orderstatus");
                    _dirtyCount++;
                }

                if (pObject.isDeadlineModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("deadline");
                    _dirtyCount++;
                }

                if (pObject.isRegdateModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("regdate");
                    _dirtyCount++;
                }

                if (pObject.isRegbyidModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("regbyid");
                    _dirtyCount++;
                }

                if (pObject.isUpdatedonModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("updatedon");
                    _dirtyCount++;
                }

                if (pObject.isNoteModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("note");
                    _dirtyCount++;
                }

                if (pObject.isRnameModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("rname");
                    _dirtyCount++;
                }

                if (pObject.isCodeModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("code");
                    _dirtyCount++;
                }

                if (pObject.isHnameModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("hname");
                    _dirtyCount++;
                }

                if (pObject.isAssignedtoModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("assignedto");
                    _dirtyCount++;
                }

                _sql.append(") values (");
                if(_dirtyCount > 0) {
                    _sql.append("?");
                    for(int i = 1; i < _dirtyCount; i++) {
                        _sql.append(",?");
                    }
                }
                _sql.append(")");

                ps = c.prepareStatement(_sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                _dirtyCount = 0;

                if (pObject.isWorkorderidModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getWorkorderid());
                }
    
                if (pObject.isNumModified()) {
                    ps.setString(++_dirtyCount, pObject.getNum());
                }
    
                if (pObject.isDescriptionModified()) {
                    ps.setString(++_dirtyCount, pObject.getDescription());
                }
    
                if (pObject.isCategoryModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getCategory());
                }
    
                if (pObject.isRoomidModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getRoomid());
                }
    
                if (pObject.isHouseunitidModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getHouseunitid());
                }
    
                if (pObject.isBlockstartModified()) {
                    ps.setTimestamp(++_dirtyCount, pObject.getBlockstart());
                }
    
                if (pObject.isBlockendModified()) {
                    ps.setTimestamp(++_dirtyCount, pObject.getBlockend());
                }
    
                if (pObject.isPriorityModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getPriority());
                }
    
                if (pObject.isAssignedtoidModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getAssignedtoid());
                }
    
                if (pObject.isOrderstatusModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getOrderstatus());
                }
    
                if (pObject.isDeadlineModified()) {
                    ps.setTimestamp(++_dirtyCount, pObject.getDeadline());
                }
    
                if (pObject.isRegdateModified()) {
                    ps.setTimestamp(++_dirtyCount, pObject.getRegdate());
                }
    
                if (pObject.isRegbyidModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getRegbyid());
                }
    
                if (pObject.isUpdatedonModified()) {
                    ps.setTimestamp(++_dirtyCount, pObject.getUpdatedon());
                }
    
                if (pObject.isNoteModified()) {
                    ps.setString(++_dirtyCount, pObject.getNote());
                }
    
                if (pObject.isRnameModified()) {
                    ps.setString(++_dirtyCount, pObject.getRname());
                }
    
                if (pObject.isCodeModified()) {
                    ps.setString(++_dirtyCount, pObject.getCode());
                }
    
                if (pObject.isHnameModified()) {
                    ps.setString(++_dirtyCount, pObject.getHname());
                }
    
                if (pObject.isAssignedtoModified()) {
                    ps.setString(++_dirtyCount, pObject.getAssignedto());
                }
    
                ps.executeUpdate();
    
                pObject.isNew(false);
                pObject.resetIsModified();
                afterInsert(pObject); // listener callback
            }
            else 
            { // UPDATE 
                beforeUpdate(pObject); // listener callback
                _sql = new StringBuffer("UPDATE v_workorder SET ");
                boolean useComma=false;

                if (pObject.isWorkorderidModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("workorderid").append("=?");
                }

                if (pObject.isNumModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("num").append("=?");
                }

                if (pObject.isDescriptionModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("description").append("=?");
                }

                if (pObject.isCategoryModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("category").append("=?");
                }

                if (pObject.isRoomidModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("roomid").append("=?");
                }

                if (pObject.isHouseunitidModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("houseunitid").append("=?");
                }

                if (pObject.isBlockstartModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("blockstart").append("=?");
                }

                if (pObject.isBlockendModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("blockend").append("=?");
                }

                if (pObject.isPriorityModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("priority").append("=?");
                }

                if (pObject.isAssignedtoidModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("assignedtoid").append("=?");
                }

                if (pObject.isOrderstatusModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("orderstatus").append("=?");
                }

                if (pObject.isDeadlineModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("deadline").append("=?");
                }

                if (pObject.isRegdateModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("regdate").append("=?");
                }

                if (pObject.isRegbyidModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("regbyid").append("=?");
                }

                if (pObject.isUpdatedonModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("updatedon").append("=?");
                }

                if (pObject.isNoteModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("note").append("=?");
                }

                if (pObject.isRnameModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("rname").append("=?");
                }

                if (pObject.isCodeModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("code").append("=?");
                }

                if (pObject.isHnameModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("hname").append("=?");
                }

                if (pObject.isAssignedtoModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("assignedto").append("=?");
                }
                _sql.append("");
                ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                int _dirtyCount = 0;

                if (pObject.isWorkorderidModified()) {
                      Manager.setLong(ps, ++_dirtyCount, pObject.getWorkorderid());
                }

                if (pObject.isNumModified()) {
                      ps.setString(++_dirtyCount, pObject.getNum());
                }

                if (pObject.isDescriptionModified()) {
                      ps.setString(++_dirtyCount, pObject.getDescription());
                }

                if (pObject.isCategoryModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getCategory());
                }

                if (pObject.isRoomidModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getRoomid());
                }

                if (pObject.isHouseunitidModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getHouseunitid());
                }

                if (pObject.isBlockstartModified()) {
                      ps.setTimestamp(++_dirtyCount, pObject.getBlockstart());
                }

                if (pObject.isBlockendModified()) {
                      ps.setTimestamp(++_dirtyCount, pObject.getBlockend());
                }

                if (pObject.isPriorityModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getPriority());
                }

                if (pObject.isAssignedtoidModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getAssignedtoid());
                }

                if (pObject.isOrderstatusModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getOrderstatus());
                }

                if (pObject.isDeadlineModified()) {
                      ps.setTimestamp(++_dirtyCount, pObject.getDeadline());
                }

                if (pObject.isRegdateModified()) {
                      ps.setTimestamp(++_dirtyCount, pObject.getRegdate());
                }

                if (pObject.isRegbyidModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getRegbyid());
                }

                if (pObject.isUpdatedonModified()) {
                      ps.setTimestamp(++_dirtyCount, pObject.getUpdatedon());
                }

                if (pObject.isNoteModified()) {
                      ps.setString(++_dirtyCount, pObject.getNote());
                }

                if (pObject.isRnameModified()) {
                      ps.setString(++_dirtyCount, pObject.getRname());
                }

                if (pObject.isCodeModified()) {
                      ps.setString(++_dirtyCount, pObject.getCode());
                }

                if (pObject.isHnameModified()) {
                      ps.setString(++_dirtyCount, pObject.getHname());
                }

                if (pObject.isAssignedtoModified()) {
                      ps.setString(++_dirtyCount, pObject.getAssignedto());
                }
    
                if (_dirtyCount == 0) {
                     return pObject;
                }
    
                ps.executeUpdate();
                pObject.resetIsModified();
                afterUpdate(pObject); // listener callback
            }
    
            return pObject;
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    /**
     * Saves an array of VWorkorderBean pObjects into the database.
     *
     * @param pObjects the VWorkorderBean pObject table to be saved
     * @return the saved VWorkorderBean array.
     */
    //65
    public VWorkorderBean[] save(VWorkorderBean[] pObjects) throws SQLException 
    {
        for (int iIndex = 0; iIndex < pObjects.length; iIndex ++){
            save(pObjects[iIndex]);
        }
        return pObjects;
    }



    ///////////////////////////////////////////////////////////////////////
    // USING TEMPLATE 
    ///////////////////////////////////////////////////////////////////////
    /**
     * Loads a unique VWorkorderBean pObject from a template one giving a c
     *
     * @param pObject the VWorkorderBean pObject to look for
     * @return the pObject matching the template
     */
    //85
    public VWorkorderBean loadUniqueUsingTemplate(VWorkorderBean pObject) throws SQLException
    {
         VWorkorderBean[] pReturn = loadUsingTemplate(pObject);
         if (pReturn.length == 0)
             return null;
         if (pReturn.length > 1)
             throw new SQLException("More than one element !!");
         return pReturn[0];
     }

    /**
     * Loads an array of VWorkorderBean from a template one.
     *
     * @param pObject the VWorkorderBean template to look for
     * @return all the VWorkorderBean matching the template
     */
    //88
    public VWorkorderBean[] loadUsingTemplate(VWorkorderBean pObject) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer where = new StringBuffer("");
        StringBuffer _sql = new StringBuffer("SELECT " + ALL_FIELDS + " from v_workorder WHERE ");
        StringBuffer _sqlWhere = new StringBuffer("");
        try
        {
            int _dirtyCount = 0;
    
             if (pObject.isWorkorderidModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("workorderid= ?");
             }
    
             if (pObject.isNumModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("num= ?");
             }
    
             if (pObject.isDescriptionModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("description= ?");
             }
    
             if (pObject.isCategoryModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("category= ?");
             }
    
             if (pObject.isRoomidModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("roomid= ?");
             }
    
             if (pObject.isHouseunitidModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("houseunitid= ?");
             }
    
             if (pObject.isBlockstartModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("blockstart= ?");
             }
    
             if (pObject.isBlockendModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("blockend= ?");
             }
    
             if (pObject.isPriorityModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("priority= ?");
             }
    
             if (pObject.isAssignedtoidModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("assignedtoid= ?");
             }
    
             if (pObject.isOrderstatusModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("orderstatus= ?");
             }
    
             if (pObject.isDeadlineModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("deadline= ?");
             }
    
             if (pObject.isRegdateModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("regdate= ?");
             }
    
             if (pObject.isRegbyidModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("regbyid= ?");
             }
    
             if (pObject.isUpdatedonModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("updatedon= ?");
             }
    
             if (pObject.isNoteModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("note= ?");
             }
    
             if (pObject.isRnameModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("rname= ?");
             }
    
             if (pObject.isCodeModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("code= ?");
             }
    
             if (pObject.isHnameModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("hname= ?");
             }
    
             if (pObject.isAssignedtoModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("assignedto= ?");
             }
    
             if (_dirtyCount == 0) {
                 throw new SQLException ("The pObject to look for is invalid : not initialized !");
             }
             _sql.append(_sqlWhere);
             c = getConnection();
             ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
             _dirtyCount = 0;
    
             if (pObject.isWorkorderidModified()) {
                 Manager.setLong(ps, ++_dirtyCount, pObject.getWorkorderid());
             }
    
             if (pObject.isNumModified()) {
                 ps.setString(++_dirtyCount, pObject.getNum());
             }
    
             if (pObject.isDescriptionModified()) {
                 ps.setString(++_dirtyCount, pObject.getDescription());
             }
    
             if (pObject.isCategoryModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getCategory());
             }
    
             if (pObject.isRoomidModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getRoomid());
             }
    
             if (pObject.isHouseunitidModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getHouseunitid());
             }
    
             if (pObject.isBlockstartModified()) {
                 ps.setTimestamp(++_dirtyCount, pObject.getBlockstart());
             }
    
             if (pObject.isBlockendModified()) {
                 ps.setTimestamp(++_dirtyCount, pObject.getBlockend());
             }
    
             if (pObject.isPriorityModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getPriority());
             }
    
             if (pObject.isAssignedtoidModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getAssignedtoid());
             }
    
             if (pObject.isOrderstatusModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getOrderstatus());
             }
    
             if (pObject.isDeadlineModified()) {
                 ps.setTimestamp(++_dirtyCount, pObject.getDeadline());
             }
    
             if (pObject.isRegdateModified()) {
                 ps.setTimestamp(++_dirtyCount, pObject.getRegdate());
             }
    
             if (pObject.isRegbyidModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getRegbyid());
             }
    
             if (pObject.isUpdatedonModified()) {
                 ps.setTimestamp(++_dirtyCount, pObject.getUpdatedon());
             }
    
             if (pObject.isNoteModified()) {
                 ps.setString(++_dirtyCount, pObject.getNote());
             }
    
             if (pObject.isRnameModified()) {
                 ps.setString(++_dirtyCount, pObject.getRname());
             }
    
             if (pObject.isCodeModified()) {
                 ps.setString(++_dirtyCount, pObject.getCode());
             }
    
             if (pObject.isHnameModified()) {
                 ps.setString(++_dirtyCount, pObject.getHname());
             }
    
             if (pObject.isAssignedtoModified()) {
                 ps.setString(++_dirtyCount, pObject.getAssignedto());
             }
    
             ps.executeQuery();
             return loadByPreparedStatement(ps);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }
    /**
     * Deletes rows using a VWorkorderBean template.
     *
     * @param pObject the VWorkorderBean object(s) to be deleted
     * @return the number of deleted objects
     */
    //63
    public int deleteUsingTemplate(VWorkorderBean pObject) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;
    
        try 
        {
            sql = new StringBuffer("DELETE FROM v_workorder WHERE ");
            int _dirtyAnd = 0;
            if (pObject.isWorkorderidInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("workorderid").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isNumInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("num").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isDescriptionInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("description").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isCategoryInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("category").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isRoomidInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("roomid").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isHouseunitidInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("houseunitid").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isBlockstartInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("blockstart").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isBlockendInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("blockend").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isPriorityInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("priority").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isAssignedtoidInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("assignedtoid").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isOrderstatusInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("orderstatus").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isDeadlineInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("deadline").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isRegdateInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("regdate").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isRegbyidInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("regbyid").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isUpdatedonInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("updatedon").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isNoteInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("note").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isRnameInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("rname").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isCodeInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("code").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isHnameInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("hname").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isAssignedtoInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("assignedto").append("=?");
                _dirtyAnd ++;
            }
    
            c = getConnection();
            ps = c.prepareStatement(sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            int _dirtyCount = 0;
    
            if (pObject.isWorkorderidInitialized()) {
                Manager.setLong(ps, ++_dirtyCount, pObject.getWorkorderid());
            }
    
            if (pObject.isNumInitialized()) {
                ps.setString(++_dirtyCount, pObject.getNum());
            }
    
            if (pObject.isDescriptionInitialized()) {
                ps.setString(++_dirtyCount, pObject.getDescription());
            }
    
            if (pObject.isCategoryInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getCategory());
            }
    
            if (pObject.isRoomidInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getRoomid());
            }
    
            if (pObject.isHouseunitidInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getHouseunitid());
            }
    
            if (pObject.isBlockstartInitialized()) {
                ps.setTimestamp(++_dirtyCount, pObject.getBlockstart());
            }
    
            if (pObject.isBlockendInitialized()) {
                ps.setTimestamp(++_dirtyCount, pObject.getBlockend());
            }
    
            if (pObject.isPriorityInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getPriority());
            }
    
            if (pObject.isAssignedtoidInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getAssignedtoid());
            }
    
            if (pObject.isOrderstatusInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getOrderstatus());
            }
    
            if (pObject.isDeadlineInitialized()) {
                ps.setTimestamp(++_dirtyCount, pObject.getDeadline());
            }
    
            if (pObject.isRegdateInitialized()) {
                ps.setTimestamp(++_dirtyCount, pObject.getRegdate());
            }
    
            if (pObject.isRegbyidInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getRegbyid());
            }
    
            if (pObject.isUpdatedonInitialized()) {
                ps.setTimestamp(++_dirtyCount, pObject.getUpdatedon());
            }
    
            if (pObject.isNoteInitialized()) {
                ps.setString(++_dirtyCount, pObject.getNote());
            }
    
            if (pObject.isRnameInitialized()) {
                ps.setString(++_dirtyCount, pObject.getRname());
            }
    
            if (pObject.isCodeInitialized()) {
                ps.setString(++_dirtyCount, pObject.getCode());
            }
    
            if (pObject.isHnameInitialized()) {
                ps.setString(++_dirtyCount, pObject.getHname());
            }
    
            if (pObject.isAssignedtoInitialized()) {
                ps.setString(++_dirtyCount, pObject.getAssignedto());
            }
    
            int _rows = ps.executeUpdate();
            return _rows;
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // COUNT 
    ///////////////////////////////////////////////////////////////////////

    /**
     * Retrieves the number of rows of the table v_workorder.
     *
     * @return the number of rows returned
     */
    //78
    public int countAll() throws SQLException
    {
        return countWhere("");
    }



    /**
     * Retrieves the number of rows of the table v_workorder with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     */
    public int countWhere(String where) throws SQLException
    {
        String sql = "select count(*) as MCOUNT from v_workorder " + where;
        Connection c = null;
        Statement pStatement = null;
        ResultSet rs =  null;
        try 
        {
            int iReturn = -1;    
            c = getConnection();
            pStatement = c.createStatement();
            rs =  pStatement.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1)
                return iReturn;
        }
        finally
        {
            getManager().close(pStatement, rs);
            freeConnection(c);
        }
       throw new SQLException("Error in countWhere");
    }

    /**
     * Retrieves the number of rows of the table v_workorder with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     */
    //82
    int countByPreparedStatement(PreparedStatement ps) throws SQLException
    {
        ResultSet rs =  null;
        try 
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next())
                iReturn = rs.getInt("MCOUNT");
            if (iReturn != -1)
                return iReturn;
        }
        finally
        {
            getManager().close(rs);
        }
       throw new SQLException("Error in countByPreparedStatement");
    }

    /**
     * Looks for the number of elements of a specific VWorkorderBean pObject given a c
     *
     * @param pObject the VWorkorderBean pObject to look for
     * @return the number of rows returned
     */
    //83
    public int countUsingTemplate(VWorkorderBean pObject) throws SQLException
    {
        StringBuffer where = new StringBuffer("");
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer _sql = null;
        StringBuffer _sqlWhere = null;
    
        try
        {
                _sql = new StringBuffer("SELECT count(*) as MCOUNT  from v_workorder WHERE ");
                _sqlWhere = new StringBuffer("");
                int _dirtyCount = 0;
    
                if (pObject.isWorkorderidModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("workorderid= ?");
                }
    
                if (pObject.isNumModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("num= ?");
                }
    
                if (pObject.isDescriptionModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("description= ?");
                }
    
                if (pObject.isCategoryModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("category= ?");
                }
    
                if (pObject.isRoomidModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("roomid= ?");
                }
    
                if (pObject.isHouseunitidModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("houseunitid= ?");
                }
    
                if (pObject.isBlockstartModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("blockstart= ?");
                }
    
                if (pObject.isBlockendModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("blockend= ?");
                }
    
                if (pObject.isPriorityModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("priority= ?");
                }
    
                if (pObject.isAssignedtoidModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("assignedtoid= ?");
                }
    
                if (pObject.isOrderstatusModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("orderstatus= ?");
                }
    
                if (pObject.isDeadlineModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("deadline= ?");
                }
    
                if (pObject.isRegdateModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("regdate= ?");
                }
    
                if (pObject.isRegbyidModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("regbyid= ?");
                }
    
                if (pObject.isUpdatedonModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("updatedon= ?");
                }
    
                if (pObject.isNoteModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("note= ?");
                }
    
                if (pObject.isRnameModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("rname= ?");
                }
    
                if (pObject.isCodeModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("code= ?");
                }
    
                if (pObject.isHnameModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("hname= ?");
                }
    
                if (pObject.isAssignedtoModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("assignedto= ?");
                }
    
                if (_dirtyCount == 0)
                   throw new SQLException ("The pObject to look is unvalid : not initialized !");
    
                _sql.append(_sqlWhere);
                c = getConnection();
                ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    
                _dirtyCount = 0;
    
                if (pObject.isWorkorderidModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getWorkorderid());
                }
    
                if (pObject.isNumModified()) {
                    ps.setString(++_dirtyCount, pObject.getNum());
                }
    
                if (pObject.isDescriptionModified()) {
                    ps.setString(++_dirtyCount, pObject.getDescription());
                }
    
                if (pObject.isCategoryModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getCategory());
                }
    
                if (pObject.isRoomidModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getRoomid());
                }
    
                if (pObject.isHouseunitidModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getHouseunitid());
                }
    
                if (pObject.isBlockstartModified()) {
                    ps.setTimestamp(++_dirtyCount, pObject.getBlockstart());
                }
    
                if (pObject.isBlockendModified()) {
                    ps.setTimestamp(++_dirtyCount, pObject.getBlockend());
                }
    
                if (pObject.isPriorityModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getPriority());
                }
    
                if (pObject.isAssignedtoidModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getAssignedtoid());
                }
    
                if (pObject.isOrderstatusModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getOrderstatus());
                }
    
                if (pObject.isDeadlineModified()) {
                    ps.setTimestamp(++_dirtyCount, pObject.getDeadline());
                }
    
                if (pObject.isRegdateModified()) {
                    ps.setTimestamp(++_dirtyCount, pObject.getRegdate());
                }
    
                if (pObject.isRegbyidModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getRegbyid());
                }
    
                if (pObject.isUpdatedonModified()) {
                    ps.setTimestamp(++_dirtyCount, pObject.getUpdatedon());
                }
    
                if (pObject.isNoteModified()) {
                    ps.setString(++_dirtyCount, pObject.getNote());
                }
    
                if (pObject.isRnameModified()) {
                    ps.setString(++_dirtyCount, pObject.getRname());
                }
    
                if (pObject.isCodeModified()) {
                    ps.setString(++_dirtyCount, pObject.getCode());
                }
    
                if (pObject.isHnameModified()) {
                    ps.setString(++_dirtyCount, pObject.getHname());
                }
    
                if (pObject.isAssignedtoModified()) {
                    ps.setString(++_dirtyCount, pObject.getAssignedto());
                }
    
                return countByPreparedStatement(ps);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // DECODE RESULT SET 
    ///////////////////////////////////////////////////////////////////////
    /**
     * Transforms a ResultSet iterating on the v_workorder on a VWorkorderBean pObject.
     *
     * @param rs the ResultSet to be transformed
     * @return pObject resulting VWorkorderBean pObject
     */
    //72
    public VWorkorderBean decodeRow(ResultSet rs) throws SQLException
    {
        VWorkorderBean pObject = createVWorkorderBean();
        pObject.setWorkorderid(Manager.getLong(rs, 1));
        pObject.setNum(rs.getString(2));
        pObject.setDescription(rs.getString(3));
        pObject.setCategory(Manager.getInteger(rs, 4));
        pObject.setRoomid(Manager.getInteger(rs, 5));
        pObject.setHouseunitid(Manager.getInteger(rs, 6));
        pObject.setBlockstart(rs.getTimestamp(7));
        pObject.setBlockend(rs.getTimestamp(8));
        pObject.setPriority(Manager.getInteger(rs, 9));
        pObject.setAssignedtoid(Manager.getInteger(rs, 10));
        pObject.setOrderstatus(Manager.getInteger(rs, 11));
        pObject.setDeadline(rs.getTimestamp(12));
        pObject.setRegdate(rs.getTimestamp(13));
        pObject.setRegbyid(Manager.getInteger(rs, 14));
        pObject.setUpdatedon(rs.getTimestamp(15));
        pObject.setNote(rs.getString(16));
        pObject.setRname(rs.getString(17));
        pObject.setCode(rs.getString(18));
        pObject.setHname(rs.getString(19));
        pObject.setAssignedto(rs.getString(20));

        pObject.isNew(false);
        pObject.resetIsModified();

        return pObject;
    }

    /**
     * Transforms a ResultSet iterating on the v_workorder table on a VWorkorderBean pObject according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return pObject resulting VWorkorderBean pObject
     */
    //73
    public VWorkorderBean decodeRow(ResultSet rs, int[] fieldList) throws SQLException
    {
        VWorkorderBean pObject = createVWorkorderBean();
        int pos = 0;
        for(int i = 0; i < fieldList.length; i++)
        {
            switch(fieldList[i]) {
                case ID_WORKORDERID:
                    ++pos;
                    pObject.setWorkorderid(Manager.getLong(rs, pos));
                    break;
                case ID_NUM:
                    ++pos;
                    pObject.setNum(rs.getString(pos));
                    break;
                case ID_DESCRIPTION:
                    ++pos;
                    pObject.setDescription(rs.getString(pos));
                    break;
                case ID_CATEGORY:
                    ++pos;
                    pObject.setCategory(Manager.getInteger(rs, pos));
                    break;
                case ID_ROOMID:
                    ++pos;
                    pObject.setRoomid(Manager.getInteger(rs, pos));
                    break;
                case ID_HOUSEUNITID:
                    ++pos;
                    pObject.setHouseunitid(Manager.getInteger(rs, pos));
                    break;
                case ID_BLOCKSTART:
                    ++pos;
                    pObject.setBlockstart(rs.getTimestamp(pos));
                    break;
                case ID_BLOCKEND:
                    ++pos;
                    pObject.setBlockend(rs.getTimestamp(pos));
                    break;
                case ID_PRIORITY:
                    ++pos;
                    pObject.setPriority(Manager.getInteger(rs, pos));
                    break;
                case ID_ASSIGNEDTOID:
                    ++pos;
                    pObject.setAssignedtoid(Manager.getInteger(rs, pos));
                    break;
                case ID_ORDERSTATUS:
                    ++pos;
                    pObject.setOrderstatus(Manager.getInteger(rs, pos));
                    break;
                case ID_DEADLINE:
                    ++pos;
                    pObject.setDeadline(rs.getTimestamp(pos));
                    break;
                case ID_REGDATE:
                    ++pos;
                    pObject.setRegdate(rs.getTimestamp(pos));
                    break;
                case ID_REGBYID:
                    ++pos;
                    pObject.setRegbyid(Manager.getInteger(rs, pos));
                    break;
                case ID_UPDATEDON:
                    ++pos;
                    pObject.setUpdatedon(rs.getTimestamp(pos));
                    break;
                case ID_NOTE:
                    ++pos;
                    pObject.setNote(rs.getString(pos));
                    break;
                case ID_RNAME:
                    ++pos;
                    pObject.setRname(rs.getString(pos));
                    break;
                case ID_CODE:
                    ++pos;
                    pObject.setCode(rs.getString(pos));
                    break;
                case ID_HNAME:
                    ++pos;
                    pObject.setHname(rs.getString(pos));
                    break;
                case ID_ASSIGNEDTO:
                    ++pos;
                    pObject.setAssignedto(rs.getString(pos));
                    break;
            }
        }
        pObject.isNew(false);
        pObject.resetIsModified();

        return pObject;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of VWorkorderBean 
     */
    //41
    public VWorkorderBean[] loadByPreparedStatement(PreparedStatement ps) throws SQLException
    {
        return loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of VWorkorderBean 
     */
    public VWorkorderBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws SQLException
    {
        ResultSet rs =  null;
        java.util.ArrayList v =  null;
        try
        {
            rs =  ps.executeQuery();
            v = new java.util.ArrayList();
            while(rs.next())
            {
                if(fieldList == null)
                    v.add(decodeRow(rs));
                else 
                    v.add(decodeRow(rs, fieldList));
            }
            return (VWorkorderBean[])v.toArray(new VWorkorderBean[0]);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
            getManager().close(rs);
        }
    }

    ///////////////////////////////////////////////////////////////////////
    // LISTENER 
    ///////////////////////////////////////////////////////////////////////
    private VWorkorderListener listener = null;

    /**
     * Registers a unique VWorkorderListener listener.
     */
    //66.5
    public void registerListener(VWorkorderListener listener) {
        this.listener = listener;
    }

    /**
     * Before the save of the VWorkorderBean pObject.
     *
     * @param pObject the VWorkorderBean pObject to be saved
     */
    //67
    void beforeInsert(VWorkorderBean pObject) throws SQLException {
        if (listener != null)
            listener.beforeInsert(pObject);
    }

    /**
     * After the save of the VWorkorderBean pObject.
     *
     * @param pObject the VWorkorderBean pObject to be saved
     */
    //68
    void afterInsert(VWorkorderBean pObject) throws SQLException {
        if (listener != null)
            listener.afterInsert(pObject);
    }

    /**
     * Before the update of the VWorkorderBean pObject.
     *
     * @param pObject the VWorkorderBean pObject to be updated
     */
    //69
    void beforeUpdate(VWorkorderBean pObject) throws SQLException {
        if (listener != null)
            listener.beforeUpdate(pObject);
    }

    /**
     * After the update of the VWorkorderBean pObject.
     *
     * @param pObject the VWorkorderBean pObject to be updated
     */
    //70
    void afterUpdate(VWorkorderBean pObject) throws SQLException {
        if (listener != null)
            listener.afterUpdate(pObject);
    }

    ///////////////////////////////////////////////////////////////////////
    // UTILS  
    ///////////////////////////////////////////////////////////////////////

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //2
    Manager getManager() {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    void freeConnection(Connection c) {
        getManager().releaseConnection(c); // back to pool
    }
    /**
     * Gets the connection.
     */
    Connection getConnection() throws SQLException {
        return getManager().getConnection();
    }

// class+ 

// class- 

}
