// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.SQLException;
// imports+ 

// imports- 


/**
 * Listener that is notified of displaysettings table changes.
 */
public interface DisplaysettingsListener
// extends+ 

// extends- 
{
    /**
     * Invoked just before inserting a DisplaysettingsBean record into the database.
     *
     * @param pObject the DisplaysettingsBean that is about to be inserted
     */
    public void beforeInsert(DisplaysettingsBean pObject) throws SQLException;


    /**
     * Invoked just after a DisplaysettingsBean record is inserted in the database.
     *
     * @param pObject the DisplaysettingsBean that was just inserted
     */
    public void afterInsert(DisplaysettingsBean pObject) throws SQLException;


    /**
     * Invoked just before updating a DisplaysettingsBean record in the database.
     *
     * @param pObject the DisplaysettingsBean that is about to be updated
     */
    public void beforeUpdate(DisplaysettingsBean pObject) throws SQLException;


    /**
     * Invoked just after updating a DisplaysettingsBean record in the database.
     *
     * @param pObject the DisplaysettingsBean that was just updated
     */
    public void afterUpdate(DisplaysettingsBean pObject) throws SQLException;


// class+ 

// class- 
}
