// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.sql.*;
// imports+ 

// imports- 

/**
 * Handles database calls for the extrachargefolio table.
 */
public class ExtrachargefolioManager
// extends+ 

// extends- 
{

    /**
     * Column folioitemid of type Types.BIGINT mapped to Long.
     */
    public static final int ID_FOLIOITEMID = 0;
    public static final int TYPE_FOLIOITEMID = Types.BIGINT;
    public static final String NAME_FOLIOITEMID = "folioitemid";

    /**
     * Column extrachargeid of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_EXTRACHARGEID = 1;
    public static final int TYPE_EXTRACHARGEID = Types.INTEGER;
    public static final String NAME_EXTRACHARGEID = "extrachargeid";

    /**
     * Column rate of type Types.DOUBLE mapped to Double.
     */
    public static final int ID_RATE = 2;
    public static final int TYPE_RATE = Types.DOUBLE;
    public static final String NAME_RATE = "rate";

    /**
     * Column postingtype of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_POSTINGTYPE = 3;
    public static final int TYPE_POSTINGTYPE = Types.INTEGER;
    public static final String NAME_POSTINGTYPE = "postingtype";

    /**
     * Column chargeapplyrieson of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_CHARGEAPPLYRIESON = 4;
    public static final int TYPE_CHARGEAPPLYRIESON = Types.INTEGER;
    public static final String NAME_CHARGEAPPLYRIESON = "chargeapplyrieson";

    /**
     * Column adult of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_ADULT = 5;
    public static final int TYPE_ADULT = Types.INTEGER;
    public static final String NAME_ADULT = "adult";

    /**
     * Column child of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_CHILD = 6;
    public static final int TYPE_CHILD = Types.INTEGER;
    public static final String NAME_CHILD = "child";

    /**
     * Column qty of type Types.INTEGER mapped to Integer.
     */
    public static final int ID_QTY = 7;
    public static final int TYPE_QTY = Types.INTEGER;
    public static final String NAME_QTY = "qty";


    private static final String TABLE_NAME = "extrachargefolio";

    /**
     * Create an array of type string containing all the fields of the extrachargefolio table.
     */
    private static final String[] FIELD_NAMES = 
    {
        "extrachargefolio.folioitemid"
        ,"extrachargefolio.extrachargeid"
        ,"extrachargefolio.rate"
        ,"extrachargefolio.postingtype"
        ,"extrachargefolio.chargeapplyrieson"
        ,"extrachargefolio.adult"
        ,"extrachargefolio.child"
        ,"extrachargefolio.qty"
    };

    /**
     * Field that contains the comma separated fields of the extrachargefolio table.
     */
    private static final String ALL_FIELDS = "extrachargefolio.folioitemid"
                            + ",extrachargefolio.extrachargeid"
                            + ",extrachargefolio.rate"
                            + ",extrachargefolio.postingtype"
                            + ",extrachargefolio.chargeapplyrieson"
                            + ",extrachargefolio.adult"
                            + ",extrachargefolio.child"
                            + ",extrachargefolio.qty";

    private static ExtrachargefolioManager singleton = new ExtrachargefolioManager();

    /**
     * Get the ExtrachargefolioManager singleton.
     *
     * @return ExtrachargefolioManager 
     */
    synchronized public static ExtrachargefolioManager getInstance()
    {
        return singleton;
    }

    /**
     * Sets your own ExtrachargefolioManager instance.
     <br>
     * This is optional, by default we provide it for you.
     */
    synchronized public static void setInstance(ExtrachargefolioManager instance)
    {
        singleton = instance;
    }


    /**
     * Creates a new ExtrachargefolioBean instance.
     *
     * @return the new ExtrachargefolioBean 
     */
    public ExtrachargefolioBean createExtrachargefolioBean()
    {
        return new ExtrachargefolioBean();
    }

    //////////////////////////////////////
    // PRIMARY KEY METHODS
    //////////////////////////////////////

    /**
     * Loads a ExtrachargefolioBean from the extrachargefolio using its key fields.
     *
     * @return a unique ExtrachargefolioBean 
     */
    //12
    public ExtrachargefolioBean loadByPrimaryKey(Long folioitemid, Integer extrachargeid) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try 
        {
            c = getConnection();
            ps = c.prepareStatement("SELECT " + ALL_FIELDS + " FROM extrachargefolio WHERE extrachargefolio.folioitemid=? and extrachargefolio.extrachargeid=?",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Manager.setLong(ps, 1, folioitemid);
            Manager.setInteger(ps, 2, extrachargeid);
            ExtrachargefolioBean pReturn[] = loadByPreparedStatement(ps);
            if (pReturn.length < 1)
                return null;
            else
                return pReturn[0];
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }

    /**
     * Deletes rows according to its keys.
     *
     * @return the number of deleted rows
     */
    //60
    public int deleteByPrimaryKey(Long folioitemid, Integer extrachargeid) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = getConnection();
            ps = c.prepareStatement("DELETE from extrachargefolio WHERE extrachargefolio.folioitemid=? and extrachargefolio.extrachargeid=?",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Manager.setLong(ps, 1, folioitemid);
            Manager.setInteger(ps, 2, extrachargeid);
            return ps.executeUpdate();
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from extrachargefolio.
     *
     * @return an array of ExtrachargefolioManager pObject
     */
    //38
    public ExtrachargefolioBean[] loadAll() throws SQLException 
    {
        Connection c = null;
        PreparedStatement ps = null;
        try 
        {
            c = getConnection();
            ps = c.prepareStatement("SELECT " + ALL_FIELDS + " FROM extrachargefolio",ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            return loadByPreparedStatement(ps);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of ExtrachargefolioBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting ExtrachargefolioBean table 
     */
    //49
    public ExtrachargefolioBean[] loadByWhere(String where) throws SQLException
    {
        return loadByWhere(where, null);
    }

    /**
     * Retrieves an array of ExtrachargefolioBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param fieldList table of the field's associated constants
     * @return the resulting ExtrachargefolioBean table 
     */
    //51
    public ExtrachargefolioBean[] loadByWhere(String where, int[] fieldList) throws SQLException
    {
        String sql = null;
        if(fieldList == null)
            sql = "select " + ALL_FIELDS + " from extrachargefolio " + where;
        else
        {
            StringBuffer buff = new StringBuffer(128);
            buff.append("select ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0)
                    buff.append(",");
                buff.append(FIELD_NAMES[fieldList[i]]);
            }
            buff.append(" from extrachargefolio ");
            buff.append(where);
            sql = buff.toString();
            buff = null;
        }
        Connection c = null;
        Statement pStatement = null;
        ResultSet rs =  null;
        java.util.ArrayList v = null;
        try 
        {
            c = getConnection();
            pStatement = c.createStatement();
            rs =  pStatement.executeQuery(sql);
            v = new java.util.ArrayList();
            while(rs.next())
            {
                if(fieldList == null)
                    v.add(decodeRow(rs));
                else
                    v.add(decodeRow(rs, fieldList));
            }

            return (ExtrachargefolioBean[])v.toArray(new ExtrachargefolioBean[0]);
        }
        finally
        {
            if (v != null) { v.clear(); }
            getManager().close(pStatement, rs);
            freeConnection(c);
        }
    }


    /**
     * Deletes all rows from extrachargefolio table.
     * @return the number of deleted rows.
     */
    public int deleteAll() throws SQLException
    {
        return deleteByWhere("");
    }


    /**
     * Deletes rows from the extrachargefolio table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records. 
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     */
    public int deleteByWhere(String where) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = getConnection();
            String delByWhereSQL = "DELETE FROM extrachargefolio " + where;
            ps = c.prepareStatement(delByWhereSQL);
            return ps.executeUpdate();
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // SAVE 
    ///////////////////////////////////////////////////////////////////////
    /**
     * Saves the ExtrachargefolioBean pObject into the database.
     *
     * @param pObject the ExtrachargefolioBean pObject to be saved
     */
    //100
    public ExtrachargefolioBean save(ExtrachargefolioBean pObject) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer _sql = null;

        try
        {
            c = getConnection();
            if (pObject.isNew())
            { // SAVE 
                beforeInsert(pObject); // listener callback
                int _dirtyCount = 0;
                _sql = new StringBuffer("INSERT into extrachargefolio (");
    
                if (pObject.isFolioitemidModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("folioitemid");
                    _dirtyCount++;
                }

                if (pObject.isExtrachargeidModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("extrachargeid");
                    _dirtyCount++;
                }

                if (pObject.isRateModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("rate");
                    _dirtyCount++;
                }

                if (pObject.isPostingtypeModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("postingtype");
                    _dirtyCount++;
                }

                if (pObject.isChargeapplyriesonModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("chargeapplyrieson");
                    _dirtyCount++;
                }

                if (pObject.isAdultModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("adult");
                    _dirtyCount++;
                }

                if (pObject.isChildModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("child");
                    _dirtyCount++;
                }

                if (pObject.isQtyModified()) {
                    if (_dirtyCount>0) {
                        _sql.append(",");
                    }
                    _sql.append("qty");
                    _dirtyCount++;
                }

                _sql.append(") values (");
                if(_dirtyCount > 0) {
                    _sql.append("?");
                    for(int i = 1; i < _dirtyCount; i++) {
                        _sql.append(",?");
                    }
                }
                _sql.append(")");

                ps = c.prepareStatement(_sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                _dirtyCount = 0;

                if (pObject.isFolioitemidModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getFolioitemid());
                }
    
                if (pObject.isExtrachargeidModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getExtrachargeid());
                }
    
                if (pObject.isRateModified()) {
                    Manager.setDouble(ps, ++_dirtyCount, pObject.getRate());
                }
    
                if (pObject.isPostingtypeModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getPostingtype());
                }
    
                if (pObject.isChargeapplyriesonModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getChargeapplyrieson());
                }
    
                if (pObject.isAdultModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getAdult());
                }
    
                if (pObject.isChildModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getChild());
                }
    
                if (pObject.isQtyModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getQty());
                }
    
                ps.executeUpdate();
    
                pObject.isNew(false);
                pObject.resetIsModified();
                afterInsert(pObject); // listener callback
            }
            else 
            { // UPDATE 
                beforeUpdate(pObject); // listener callback
                _sql = new StringBuffer("UPDATE extrachargefolio SET ");
                boolean useComma=false;

                if (pObject.isFolioitemidModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("folioitemid").append("=?");
                }

                if (pObject.isExtrachargeidModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("extrachargeid").append("=?");
                }

                if (pObject.isRateModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("rate").append("=?");
                }

                if (pObject.isPostingtypeModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("postingtype").append("=?");
                }

                if (pObject.isChargeapplyriesonModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("chargeapplyrieson").append("=?");
                }

                if (pObject.isAdultModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("adult").append("=?");
                }

                if (pObject.isChildModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("child").append("=?");
                }

                if (pObject.isQtyModified()) {
                    if (useComma) {
                        _sql.append(",");
                    } else {
                        useComma=true;
                    }
                    _sql.append("qty").append("=?");
                }
                _sql.append(" WHERE ");
                _sql.append("extrachargefolio.folioitemid=? AND extrachargefolio.extrachargeid=?");
                ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                int _dirtyCount = 0;

                if (pObject.isFolioitemidModified()) {
                      Manager.setLong(ps, ++_dirtyCount, pObject.getFolioitemid());
                }

                if (pObject.isExtrachargeidModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getExtrachargeid());
                }

                if (pObject.isRateModified()) {
                      Manager.setDouble(ps, ++_dirtyCount, pObject.getRate());
                }

                if (pObject.isPostingtypeModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getPostingtype());
                }

                if (pObject.isChargeapplyriesonModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getChargeapplyrieson());
                }

                if (pObject.isAdultModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getAdult());
                }

                if (pObject.isChildModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getChild());
                }

                if (pObject.isQtyModified()) {
                      Manager.setInteger(ps, ++_dirtyCount, pObject.getQty());
                }
    
                if (_dirtyCount == 0) {
                     return pObject;
                }
    
                Manager.setLong(ps, ++_dirtyCount, pObject.getFolioitemid());
                Manager.setInteger(ps, ++_dirtyCount, pObject.getExtrachargeid());
                ps.executeUpdate();
                pObject.resetIsModified();
                afterUpdate(pObject); // listener callback
            }
    
            return pObject;
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    /**
     * Saves an array of ExtrachargefolioBean pObjects into the database.
     *
     * @param pObjects the ExtrachargefolioBean pObject table to be saved
     * @return the saved ExtrachargefolioBean array.
     */
    //65
    public ExtrachargefolioBean[] save(ExtrachargefolioBean[] pObjects) throws SQLException 
    {
        for (int iIndex = 0; iIndex < pObjects.length; iIndex ++){
            save(pObjects[iIndex]);
        }
        return pObjects;
    }



    ///////////////////////////////////////////////////////////////////////
    // USING TEMPLATE 
    ///////////////////////////////////////////////////////////////////////
    /**
     * Loads a unique ExtrachargefolioBean pObject from a template one giving a c
     *
     * @param pObject the ExtrachargefolioBean pObject to look for
     * @return the pObject matching the template
     */
    //85
    public ExtrachargefolioBean loadUniqueUsingTemplate(ExtrachargefolioBean pObject) throws SQLException
    {
         ExtrachargefolioBean[] pReturn = loadUsingTemplate(pObject);
         if (pReturn.length == 0)
             return null;
         if (pReturn.length > 1)
             throw new SQLException("More than one element !!");
         return pReturn[0];
     }

    /**
     * Loads an array of ExtrachargefolioBean from a template one.
     *
     * @param pObject the ExtrachargefolioBean template to look for
     * @return all the ExtrachargefolioBean matching the template
     */
    //88
    public ExtrachargefolioBean[] loadUsingTemplate(ExtrachargefolioBean pObject) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer where = new StringBuffer("");
        StringBuffer _sql = new StringBuffer("SELECT " + ALL_FIELDS + " from extrachargefolio WHERE ");
        StringBuffer _sqlWhere = new StringBuffer("");
        try
        {
            int _dirtyCount = 0;
    
             if (pObject.isFolioitemidModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("folioitemid= ?");
             }
    
             if (pObject.isExtrachargeidModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("extrachargeid= ?");
             }
    
             if (pObject.isRateModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("rate= ?");
             }
    
             if (pObject.isPostingtypeModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("postingtype= ?");
             }
    
             if (pObject.isChargeapplyriesonModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("chargeapplyrieson= ?");
             }
    
             if (pObject.isAdultModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("adult= ?");
             }
    
             if (pObject.isChildModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("child= ?");
             }
    
             if (pObject.isQtyModified()) {
                 _dirtyCount ++; 
                 _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("qty= ?");
             }
    
             if (_dirtyCount == 0) {
                 throw new SQLException ("The pObject to look for is invalid : not initialized !");
             }
             _sql.append(_sqlWhere);
             c = getConnection();
             ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
             _dirtyCount = 0;
    
             if (pObject.isFolioitemidModified()) {
                 Manager.setLong(ps, ++_dirtyCount, pObject.getFolioitemid());
             }
    
             if (pObject.isExtrachargeidModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getExtrachargeid());
             }
    
             if (pObject.isRateModified()) {
                 Manager.setDouble(ps, ++_dirtyCount, pObject.getRate());
             }
    
             if (pObject.isPostingtypeModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getPostingtype());
             }
    
             if (pObject.isChargeapplyriesonModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getChargeapplyrieson());
             }
    
             if (pObject.isAdultModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getAdult());
             }
    
             if (pObject.isChildModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getChild());
             }
    
             if (pObject.isQtyModified()) {
                 Manager.setInteger(ps, ++_dirtyCount, pObject.getQty());
             }
    
             ps.executeQuery();
             return loadByPreparedStatement(ps);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }
    /**
     * Deletes rows using a ExtrachargefolioBean template.
     *
     * @param pObject the ExtrachargefolioBean object(s) to be deleted
     * @return the number of deleted objects
     */
    //63
    public int deleteUsingTemplate(ExtrachargefolioBean pObject) throws SQLException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = null;
    
        try 
        {
            sql = new StringBuffer("DELETE FROM extrachargefolio WHERE ");
            int _dirtyAnd = 0;
            if (pObject.isFolioitemidInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("folioitemid").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isExtrachargeidInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("extrachargeid").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isRateInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("rate").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isPostingtypeInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("postingtype").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isChargeapplyriesonInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("chargeapplyrieson").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isAdultInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("adult").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isChildInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("child").append("=?");
                _dirtyAnd ++;
            }
    
            if (pObject.isQtyInitialized()) {
                if (_dirtyAnd > 0)
                    sql.append(" AND ");
                sql.append("qty").append("=?");
                _dirtyAnd ++;
            }
    
            c = getConnection();
            ps = c.prepareStatement(sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            int _dirtyCount = 0;
    
            if (pObject.isFolioitemidInitialized()) {
                Manager.setLong(ps, ++_dirtyCount, pObject.getFolioitemid());
            }
    
            if (pObject.isExtrachargeidInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getExtrachargeid());
            }
    
            if (pObject.isRateInitialized()) {
                Manager.setDouble(ps, ++_dirtyCount, pObject.getRate());
            }
    
            if (pObject.isPostingtypeInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getPostingtype());
            }
    
            if (pObject.isChargeapplyriesonInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getChargeapplyrieson());
            }
    
            if (pObject.isAdultInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getAdult());
            }
    
            if (pObject.isChildInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getChild());
            }
    
            if (pObject.isQtyInitialized()) {
                Manager.setInteger(ps, ++_dirtyCount, pObject.getQty());
            }
    
            int _rows = ps.executeUpdate();
            return _rows;
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // COUNT 
    ///////////////////////////////////////////////////////////////////////

    /**
     * Retrieves the number of rows of the table extrachargefolio.
     *
     * @return the number of rows returned
     */
    //78
    public int countAll() throws SQLException
    {
        return countWhere("");
    }



    /**
     * Retrieves the number of rows of the table extrachargefolio with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     */
    public int countWhere(String where) throws SQLException
    {
        String sql = "select count(*) as MCOUNT from extrachargefolio " + where;
        Connection c = null;
        Statement pStatement = null;
        ResultSet rs =  null;
        try 
        {
            int iReturn = -1;    
            c = getConnection();
            pStatement = c.createStatement();
            rs =  pStatement.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1)
                return iReturn;
        }
        finally
        {
            getManager().close(pStatement, rs);
            freeConnection(c);
        }
       throw new SQLException("Error in countWhere");
    }

    /**
     * Retrieves the number of rows of the table extrachargefolio with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     */
    //82
    int countByPreparedStatement(PreparedStatement ps) throws SQLException
    {
        ResultSet rs =  null;
        try 
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next())
                iReturn = rs.getInt("MCOUNT");
            if (iReturn != -1)
                return iReturn;
        }
        finally
        {
            getManager().close(rs);
        }
       throw new SQLException("Error in countByPreparedStatement");
    }

    /**
     * Looks for the number of elements of a specific ExtrachargefolioBean pObject given a c
     *
     * @param pObject the ExtrachargefolioBean pObject to look for
     * @return the number of rows returned
     */
    //83
    public int countUsingTemplate(ExtrachargefolioBean pObject) throws SQLException
    {
        StringBuffer where = new StringBuffer("");
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer _sql = null;
        StringBuffer _sqlWhere = null;
    
        try
        {
                _sql = new StringBuffer("SELECT count(*) as MCOUNT  from extrachargefolio WHERE ");
                _sqlWhere = new StringBuffer("");
                int _dirtyCount = 0;
    
                if (pObject.isFolioitemidModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("folioitemid= ?");
                }
    
                if (pObject.isExtrachargeidModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("extrachargeid= ?");
                }
    
                if (pObject.isRateModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("rate= ?");
                }
    
                if (pObject.isPostingtypeModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("postingtype= ?");
                }
    
                if (pObject.isChargeapplyriesonModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("chargeapplyrieson= ?");
                }
    
                if (pObject.isAdultModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("adult= ?");
                }
    
                if (pObject.isChildModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("child= ?");
                }
    
                if (pObject.isQtyModified()) {
                    _dirtyCount++; 
                    _sqlWhere.append((_sqlWhere.length() == 0) ? " " : " AND ").append("qty= ?");
                }
    
                if (_dirtyCount == 0)
                   throw new SQLException ("The pObject to look is unvalid : not initialized !");
    
                _sql.append(_sqlWhere);
                c = getConnection();
                ps = c.prepareStatement(_sql.toString(),ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    
                _dirtyCount = 0;
    
                if (pObject.isFolioitemidModified()) {
                    Manager.setLong(ps, ++_dirtyCount, pObject.getFolioitemid());
                }
    
                if (pObject.isExtrachargeidModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getExtrachargeid());
                }
    
                if (pObject.isRateModified()) {
                    Manager.setDouble(ps, ++_dirtyCount, pObject.getRate());
                }
    
                if (pObject.isPostingtypeModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getPostingtype());
                }
    
                if (pObject.isChargeapplyriesonModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getChargeapplyrieson());
                }
    
                if (pObject.isAdultModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getAdult());
                }
    
                if (pObject.isChildModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getChild());
                }
    
                if (pObject.isQtyModified()) {
                    Manager.setInteger(ps, ++_dirtyCount, pObject.getQty());
                }
    
                return countByPreparedStatement(ps);
        }
        finally
        {
            getManager().close(ps);
            freeConnection(c);
        }
    }



    ///////////////////////////////////////////////////////////////////////
    // DECODE RESULT SET 
    ///////////////////////////////////////////////////////////////////////
    /**
     * Transforms a ResultSet iterating on the extrachargefolio on a ExtrachargefolioBean pObject.
     *
     * @param rs the ResultSet to be transformed
     * @return pObject resulting ExtrachargefolioBean pObject
     */
    //72
    public ExtrachargefolioBean decodeRow(ResultSet rs) throws SQLException
    {
        ExtrachargefolioBean pObject = createExtrachargefolioBean();
        pObject.setFolioitemid(Manager.getLong(rs, 1));
        pObject.setExtrachargeid(Manager.getInteger(rs, 2));
        pObject.setRate(Manager.getDouble(rs, 3));
        pObject.setPostingtype(Manager.getInteger(rs, 4));
        pObject.setChargeapplyrieson(Manager.getInteger(rs, 5));
        pObject.setAdult(Manager.getInteger(rs, 6));
        pObject.setChild(Manager.getInteger(rs, 7));
        pObject.setQty(Manager.getInteger(rs, 8));

        pObject.isNew(false);
        pObject.resetIsModified();

        return pObject;
    }

    /**
     * Transforms a ResultSet iterating on the extrachargefolio table on a ExtrachargefolioBean pObject according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return pObject resulting ExtrachargefolioBean pObject
     */
    //73
    public ExtrachargefolioBean decodeRow(ResultSet rs, int[] fieldList) throws SQLException
    {
        ExtrachargefolioBean pObject = createExtrachargefolioBean();
        int pos = 0;
        for(int i = 0; i < fieldList.length; i++)
        {
            switch(fieldList[i]) {
                case ID_FOLIOITEMID:
                    ++pos;
                    pObject.setFolioitemid(Manager.getLong(rs, pos));
                    break;
                case ID_EXTRACHARGEID:
                    ++pos;
                    pObject.setExtrachargeid(Manager.getInteger(rs, pos));
                    break;
                case ID_RATE:
                    ++pos;
                    pObject.setRate(Manager.getDouble(rs, pos));
                    break;
                case ID_POSTINGTYPE:
                    ++pos;
                    pObject.setPostingtype(Manager.getInteger(rs, pos));
                    break;
                case ID_CHARGEAPPLYRIESON:
                    ++pos;
                    pObject.setChargeapplyrieson(Manager.getInteger(rs, pos));
                    break;
                case ID_ADULT:
                    ++pos;
                    pObject.setAdult(Manager.getInteger(rs, pos));
                    break;
                case ID_CHILD:
                    ++pos;
                    pObject.setChild(Manager.getInteger(rs, pos));
                    break;
                case ID_QTY:
                    ++pos;
                    pObject.setQty(Manager.getInteger(rs, pos));
                    break;
            }
        }
        pObject.isNew(false);
        pObject.resetIsModified();

        return pObject;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of ExtrachargefolioBean 
     */
    //41
    public ExtrachargefolioBean[] loadByPreparedStatement(PreparedStatement ps) throws SQLException
    {
        return loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of ExtrachargefolioBean 
     */
    public ExtrachargefolioBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws SQLException
    {
        ResultSet rs =  null;
        java.util.ArrayList v =  null;
        try
        {
            rs =  ps.executeQuery();
            v = new java.util.ArrayList();
            while(rs.next())
            {
                if(fieldList == null)
                    v.add(decodeRow(rs));
                else 
                    v.add(decodeRow(rs, fieldList));
            }
            return (ExtrachargefolioBean[])v.toArray(new ExtrachargefolioBean[0]);
        }
        finally
        {
            if (v != null) { v.clear(); v = null;}
            getManager().close(rs);
        }
    }

    ///////////////////////////////////////////////////////////////////////
    // LISTENER 
    ///////////////////////////////////////////////////////////////////////
    private ExtrachargefolioListener listener = null;

    /**
     * Registers a unique ExtrachargefolioListener listener.
     */
    //66.5
    public void registerListener(ExtrachargefolioListener listener) {
        this.listener = listener;
    }

    /**
     * Before the save of the ExtrachargefolioBean pObject.
     *
     * @param pObject the ExtrachargefolioBean pObject to be saved
     */
    //67
    void beforeInsert(ExtrachargefolioBean pObject) throws SQLException {
        if (listener != null)
            listener.beforeInsert(pObject);
    }

    /**
     * After the save of the ExtrachargefolioBean pObject.
     *
     * @param pObject the ExtrachargefolioBean pObject to be saved
     */
    //68
    void afterInsert(ExtrachargefolioBean pObject) throws SQLException {
        if (listener != null)
            listener.afterInsert(pObject);
    }

    /**
     * Before the update of the ExtrachargefolioBean pObject.
     *
     * @param pObject the ExtrachargefolioBean pObject to be updated
     */
    //69
    void beforeUpdate(ExtrachargefolioBean pObject) throws SQLException {
        if (listener != null)
            listener.beforeUpdate(pObject);
    }

    /**
     * After the update of the ExtrachargefolioBean pObject.
     *
     * @param pObject the ExtrachargefolioBean pObject to be updated
     */
    //70
    void afterUpdate(ExtrachargefolioBean pObject) throws SQLException {
        if (listener != null)
            listener.afterUpdate(pObject);
    }

    ///////////////////////////////////////////////////////////////////////
    // UTILS  
    ///////////////////////////////////////////////////////////////////////

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //2
    Manager getManager() {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    void freeConnection(Connection c) {
        getManager().releaseConnection(c); // back to pool
    }
    /**
     * Gets the connection.
     */
    Connection getConnection() throws SQLException {
        return getManager().getConnection();
    }

// class+ 

// class- 
}
