// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.util.Comparator;
// imports+ 

// imports- 


/**
 * Comparator class is used to sort the ExtrachecktypeBean objects.
 */
public class ExtrachecktypeComparator implements Comparator
// extends+ 

// extends- 

{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for ExtrachecktypeComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new ExtrachecktypeComparator(ExtrachecktypeManager.EXTRACHECKTYPEID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>ExtrachecktypeManager.ID_EXTRACHECKTYPEID
     *   <li>ExtrachecktypeManager.ID_NAME
     *   <li>ExtrachecktypeManager.ID_PREFIX
     *   <li>ExtrachecktypeManager.ID_STARTVALUE
     *   <li>ExtrachecktypeManager.ID_RESETTYPE
     * </ul>
     */
    public ExtrachecktypeComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for ExtrachecktypeComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new ExtrachecktypeComparator(ExtrachecktypeManager.EXTRACHECKTYPEID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>ExtrachecktypeManager.ID_EXTRACHECKTYPEID
     *   <li>ExtrachecktypeManager.ID_NAME
     *   <li>ExtrachecktypeManager.ID_AUTOINCREMENT
     *   <li>ExtrachecktypeManager.ID_PREFIX
     *   <li>ExtrachecktypeManager.ID_STARTVALUE
     *   <li>ExtrachecktypeManager.ID_RESETTYPE
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public ExtrachecktypeComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        ExtrachecktypeBean b1 = (ExtrachecktypeBean)pObj1;
        ExtrachecktypeBean b2 = (ExtrachecktypeBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case ExtrachecktypeManager.ID_EXTRACHECKTYPEID:
                if (b1.getExtrachecktypeid() == null && b2.getExtrachecktypeid() != null) {
                    iReturn = -1;
                } else if (b1.getExtrachecktypeid() == null && b2.getExtrachecktypeid() == null) {
                    iReturn = 0;
                } else if (b1.getExtrachecktypeid() != null && b2.getExtrachecktypeid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getExtrachecktypeid().compareTo(b2.getExtrachecktypeid());
                }
                break;
            case ExtrachecktypeManager.ID_NAME:
                if (b1.getName() == null && b2.getName() != null) {
                    iReturn = -1;
                } else if (b1.getName() == null && b2.getName() == null) {
                    iReturn = 0;
                } else if (b1.getName() != null && b2.getName() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getName().compareTo(b2.getName());
                }
                break;
            case ExtrachecktypeManager.ID_PREFIX:
                if (b1.getPrefix() == null && b2.getPrefix() != null) {
                    iReturn = -1;
                } else if (b1.getPrefix() == null && b2.getPrefix() == null) {
                    iReturn = 0;
                } else if (b1.getPrefix() != null && b2.getPrefix() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getPrefix().compareTo(b2.getPrefix());
                }
                break;
            case ExtrachecktypeManager.ID_STARTVALUE:
                if (b1.getStartvalue() == null && b2.getStartvalue() != null) {
                    iReturn = -1;
                } else if (b1.getStartvalue() == null && b2.getStartvalue() == null) {
                    iReturn = 0;
                } else if (b1.getStartvalue() != null && b2.getStartvalue() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getStartvalue().compareTo(b2.getStartvalue());
                }
                break;
            case ExtrachecktypeManager.ID_RESETTYPE:
                if (b1.getResettype() == null && b2.getResettype() != null) {
                    iReturn = -1;
                } else if (b1.getResettype() == null && b2.getResettype() == null) {
                    iReturn = 0;
                } else if (b1.getResettype() != null && b2.getResettype() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getResettype().compareTo(b2.getResettype());
                }
                break;
            default: 
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 

}
