// --------------------------------------------------------
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
// 
// Please help us improve this tool by reporting:
//    problems,
//    suggestions,
//    feedbacks,
//    ideas,
//  to http://sourceforge.net/projects/sql2java/
// --------------------------------------------------------

package com.mysoft.hms;

import java.util.Comparator;
// imports+ 

// imports- 


/**
 * Comparator class is used to sort the MenuBean objects.
 */
public class MenuComparator implements Comparator
// extends+ 

// extends- 

{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for MenuComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new MenuComparator(MenuManager.MENUID, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>MenuManager.ID_MENUID
     *   <li>MenuManager.ID_NAME
     *   <li>MenuManager.ID_FILE
     *   <li>MenuManager.ID_PARENTID
     *   <li>MenuManager.ID_ORD
     * </ul>
     */
    public MenuComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for MenuComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new MenuComparator(MenuManager.MENUID, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>MenuManager.ID_MENUID
     *   <li>MenuManager.ID_NAME
     *   <li>MenuManager.ID_FILE
     *   <li>MenuManager.ID_PARENTID
     *   <li>MenuManager.ID_ORD
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public MenuComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        MenuBean b1 = (MenuBean)pObj1;
        MenuBean b2 = (MenuBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case MenuManager.ID_MENUID:
                if (b1.getMenuid() == null && b2.getMenuid() != null) {
                    iReturn = -1;
                } else if (b1.getMenuid() == null && b2.getMenuid() == null) {
                    iReturn = 0;
                } else if (b1.getMenuid() != null && b2.getMenuid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getMenuid().compareTo(b2.getMenuid());
                }
                break;
            case MenuManager.ID_NAME:
                if (b1.getName() == null && b2.getName() != null) {
                    iReturn = -1;
                } else if (b1.getName() == null && b2.getName() == null) {
                    iReturn = 0;
                } else if (b1.getName() != null && b2.getName() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getName().compareTo(b2.getName());
                }
                break;
            case MenuManager.ID_FILE:
                if (b1.getFile() == null && b2.getFile() != null) {
                    iReturn = -1;
                } else if (b1.getFile() == null && b2.getFile() == null) {
                    iReturn = 0;
                } else if (b1.getFile() != null && b2.getFile() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getFile().compareTo(b2.getFile());
                }
                break;
            case MenuManager.ID_PARENTID:
                if (b1.getParentid() == null && b2.getParentid() != null) {
                    iReturn = -1;
                } else if (b1.getParentid() == null && b2.getParentid() == null) {
                    iReturn = 0;
                } else if (b1.getParentid() != null && b2.getParentid() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getParentid().compareTo(b2.getParentid());
                }
                break;
            case MenuManager.ID_ORD:
                if (b1.getOrd() == null && b2.getOrd() != null) {
                    iReturn = -1;
                } else if (b1.getOrd() == null && b2.getOrd() == null) {
                    iReturn = 0;
                } else if (b1.getOrd() != null && b2.getOrd() == null) {
                    iReturn = 1;
                } else { 
                    iReturn = b1.getOrd().compareTo(b2.getOrd());
                }
                break;
            default: 
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }
// class+ 

// class- 

}
